//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AddOptionDescription {
            get {
                return ResourceManager.GetString("AddOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string AddOptionText {
            get {
                return ResourceManager.GetString("AddOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vote Option.
        /// </summary>
        internal static string AddOptionTitle {
            get {
                return ResourceManager.GetString("AddOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a voting procedure.
        /// </summary>
        internal static string AdminChooseCreateVoting {
            get {
                return ResourceManager.GetString("AdminChooseCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download signature requests from server.
        /// </summary>
        internal static string AdminChooseDownloadRequest {
            get {
                return ResourceManager.GetString("AdminChooseDownloadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload signature response to server.
        /// </summary>
        internal static string AdminChooseUploadResponse {
            get {
                return ResourceManager.GetString("AdminChooseUploadResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;heck Shares.
        /// </summary>
        internal static string AuthorityCheckShares {
            get {
                return ResourceManager.GetString("AuthorityCheckShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares where verified and accepted. Our answer was uploaded to server..
        /// </summary>
        internal static string AuthorityCheckSharesAccept {
            get {
                return ResourceManager.GetString("AuthorityCheckSharesAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares where verified but not accepted. Our answer was uploaded to server..
        /// </summary>
        internal static string AuthorityCheckSharesDecline {
            get {
                return ResourceManager.GetString("AuthorityCheckSharesDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Shares.
        /// </summary>
        internal static string AuthorityCreateShares {
            get {
                return ResourceManager.GetString("AuthorityCreateShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares created and uploaded them to server..
        /// </summary>
        internal static string AuthorityCreateSharesDone {
            get {
                return ResourceManager.GetString("AuthorityCreateSharesDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decipher.
        /// </summary>
        internal static string AuthorityDecipher {
            get {
                return ResourceManager.GetString("AuthorityDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial deciphers where calculated and uploaded to the server..
        /// </summary>
        internal static string AuthorityDecipherDone {
            get {
                return ResourceManager.GetString("AuthorityDecipherDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AuthorityListStatus {
            get {
                return ResourceManager.GetString("AuthorityListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string AuthorityListTitle {
            get {
                return ResourceManager.GetString("AuthorityListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Authority Data.
        /// </summary>
        internal static string AuthorityLoadData {
            get {
                return ResourceManager.GetString("AuthorityLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Authority Data.
        /// </summary>
        internal static string AuthoritySaveData {
            get {
                return ResourceManager.GetString("AuthoritySaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlling Authorities.
        /// </summary>
        internal static string BadShareProofControlling {
            get {
                return ResourceManager.GetString("BadShareProofControlling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing Administrator.
        /// </summary>
        internal static string BadShareProofOrganizing {
            get {
                return ResourceManager.GetString("BadShareProofOrganizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Authority.
        /// </summary>
        internal static string BadShareProofReporting {
            get {
                return ResourceManager.GetString("BadShareProofReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature:.
        /// </summary>
        internal static string BadShareProofSignature {
            get {
                return ResourceManager.GetString("BadShareProofSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Procedure.
        /// </summary>
        internal static string BadShareProofVoting {
            get {
                return ResourceManager.GetString("BadShareProofVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string BadShareProofVotingId {
            get {
                return ResourceManager.GetString("BadShareProofVotingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string BadShareProofVotingTitle {
            get {
                return ResourceManager.GetString("BadShareProofVotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        internal static string CertificateCreationDate {
            get {
                return ResourceManager.GetString("CertificateCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details....
        /// </summary>
        internal static string CertificateDetail {
            get {
                return ResourceManager.GetString("CertificateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CertificateFormCloseButton {
            get {
                return ResourceManager.GetString("CertificateFormCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Certificate.
        /// </summary>
        internal static string CertificateFormTitle {
            get {
                return ResourceManager.GetString("CertificateFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string CertificateId {
            get {
                return ResourceManager.GetString("CertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string CertificateInvalid {
            get {
                return ResourceManager.GetString("CertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string CertificateName {
            get {
                return ResourceManager.GetString("CertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CertificateSignatureId {
            get {
                return ResourceManager.GetString("CertificateSignatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string CertificateSignatureInvalid {
            get {
                return ResourceManager.GetString("CertificateSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CertificateSignatureName {
            get {
                return ResourceManager.GetString("CertificateSignatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures:.
        /// </summary>
        internal static string CertificateSignatures {
            get {
                return ResourceManager.GetString("CertificateSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CertificateSignatureStatus {
            get {
                return ResourceManager.GetString("CertificateSignatureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CertificateSignatureUnknown {
            get {
                return ResourceManager.GetString("CertificateSignatureUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string CertificateSignatureValid {
            get {
                return ResourceManager.GetString("CertificateSignatureValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        internal static string CertificateSignatureValidFrom {
            get {
                return ResourceManager.GetString("CertificateSignatureValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Until.
        /// </summary>
        internal static string CertificateSignatureValidUntil {
            get {
                return ResourceManager.GetString("CertificateSignatureValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string CertificateStatus {
            get {
                return ResourceManager.GetString("CertificateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string CertificateType {
            get {
                return ResourceManager.GetString("CertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string CertificateValid {
            get {
                return ResourceManager.GetString("CertificateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to create a certificate signature request and submit it to the server..
        /// </summary>
        internal static string CheckCertificateNeedRequest {
            get {
                return ResourceManager.GetString("CheckCertificateNeedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate signature request ist still pending on the server..
        /// </summary>
        internal static string CheckCertificatePending {
            get {
                return ResourceManager.GetString("CheckCertificatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate is valid and ready for use..
        /// </summary>
        internal static string CheckCertificateReady {
            get {
                return ResourceManager.GetString("CheckCertificateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a response to your certificate signing request and the signature was affixed to your certificate..
        /// </summary>
        internal static string CheckCertificateResponseAccept {
            get {
                return ResourceManager.GetString("CheckCertificateResponseAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a response to your certificate signing request, but the certificate authority declined your request for the following reason:.
        /// </summary>
        internal static string CheckCertificateResponseDeclined {
            get {
                return ResourceManager.GetString("CheckCertificateResponseDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a response to your certificate signing request, but it is not valid. Please context your voting administrator..
        /// </summary>
        internal static string CheckCertificateResponseInvalid {
            get {
                return ResourceManager.GetString("CheckCertificateResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create....
        /// </summary>
        internal static string ChooseCertificateCreateButton {
            get {
                return ResourceManager.GetString("ChooseCertificateCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string ChooseCertificateFullName {
            get {
                return ResourceManager.GetString("ChooseCertificateFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ChooseCertificateId {
            get {
                return ResourceManager.GetString("ChooseCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load....
        /// </summary>
        internal static string ChooseCertificateLoadButton {
            get {
                return ResourceManager.GetString("ChooseCertificateLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Certificate.
        /// </summary>
        internal static string ChooseCertificateLoadDialog {
            get {
                return ResourceManager.GetString("ChooseCertificateLoadDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ChooseCertificateType {
            get {
                return ResourceManager.GetString("ChooseCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfiy share &amp;proof....
        /// </summary>
        internal static string ChooseCertificateVerifyBadShareProof {
            get {
                return ResourceManager.GetString("ChooseCertificateVerifyBadShareProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string ContextMenuAdd {
            get {
                return ResourceManager.GetString("ContextMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted to the server. You must now wait for the certificat authority to process it..
        /// </summary>
        internal static string CreateCertificateDone {
            get {
                return ResourceManager.GetString("CreateCertificateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string CreateCertificateFirstname {
            get {
                return ResourceManager.GetString("CreateCertificateFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party function.
        /// </summary>
        internal static string CreateCertificateFunction {
            get {
                return ResourceManager.GetString("CreateCertificateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save....
        /// </summary>
        internal static string CreateCertificateSaveButton {
            get {
                return ResourceManager.GetString("CreateCertificateSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Certificate.
        /// </summary>
        internal static string CreateCertificateSaveDialog {
            get {
                return ResourceManager.GetString("CreateCertificateSaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string CreateCertificateSurname {
            get {
                return ResourceManager.GetString("CreateCertificateSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type.
        /// </summary>
        internal static string CreateCertificateType {
            get {
                return ResourceManager.GetString("CreateCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string CreateCertificateTypeAdmin {
            get {
                return ResourceManager.GetString("CreateCertificateTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Authority.
        /// </summary>
        internal static string CreateCertificateTypeAuthority {
            get {
                return ResourceManager.GetString("CreateCertificateTypeAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter.
        /// </summary>
        internal static string CreateCertificateTypeVoter {
            get {
                return ResourceManager.GetString("CreateCertificateTypeVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string CreateVotingAnswers {
            get {
                return ResourceManager.GetString("CreateVotingAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers / Voter.
        /// </summary>
        internal static string CreateVotingAnswersPerVoter {
            get {
                return ResourceManager.GetString("CreateVotingAnswersPerVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority voting file missing..
        /// </summary>
        internal static string CreateVotingAuthFileMissing {
            get {
                return ResourceManager.GetString("CreateVotingAuthFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        internal static string CreateVotingAuthorities {
            get {
                return ResourceManager.GetString("CreateVotingAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create.
        /// </summary>
        internal static string CreateVotingButton {
            get {
                return ResourceManager.GetString("CreateVotingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created voting on server..
        /// </summary>
        internal static string CreateVotingCreated {
            get {
                return ResourceManager.GetString("CreateVotingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating voting on server..
        /// </summary>
        internal static string CreateVotingCreating {
            get {
                return ResourceManager.GetString("CreateVotingCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CreateVotingDescription {
            get {
                return ResourceManager.GetString("CreateVotingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from.
        /// </summary>
        internal static string CreateVotingOpenFrom {
            get {
                return ResourceManager.GetString("CreateVotingOpenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        internal static string CreateVotingOpenUntil {
            get {
                return ResourceManager.GetString("CreateVotingOpenUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CreateVotingOptionDescription {
            get {
                return ResourceManager.GetString("CreateVotingOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string CreateVotingOptionText {
            get {
                return ResourceManager.GetString("CreateVotingOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string CreateVotingQuestion {
            get {
                return ResourceManager.GetString("CreateVotingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption.
        /// </summary>
        internal static string CreateVotingQuestionDescription {
            get {
                return ResourceManager.GetString("CreateVotingQuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string CreateVotingQuestions {
            get {
                return ResourceManager.GetString("CreateVotingQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string CreateVotingQuestionText {
            get {
                return ResourceManager.GetString("CreateVotingQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching safe prime number for crypto..
        /// </summary>
        internal static string CreateVotingSearchPrime {
            get {
                return ResourceManager.GetString("CreateVotingSearchPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CreateVotingTitle {
            get {
                return ResourceManager.GetString("CreateVotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ballots.
        /// </summary>
        internal static string InvalidBallots {
            get {
                return ResourceManager.GetString("InvalidBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voted.
        /// </summary>
        internal static string ListVotingsVoted {
            get {
                return ResourceManager.GetString("ListVotingsVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ListVotingsVotedNo {
            get {
                return ResourceManager.GetString("ListVotingsVotedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ListVotingsVotedYes {
            get {
                return ResourceManager.GetString("ListVotingsVotedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open....
        /// </summary>
        internal static string OpenSignatureResponseButton {
            get {
                return ResourceManager.GetString("OpenSignatureResponseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Signature Responses.
        /// </summary>
        internal static string OpenSignatureResponseDialog {
            get {
                return ResourceManager.GetString("OpenSignatureResponseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Client.
        /// </summary>
        internal static string PiVoteClient {
            get {
                return ResourceManager.GetString("PiVoteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root certificate file is missing..
        /// </summary>
        internal static string RootCertificateMissing {
            get {
                return ResourceManager.GetString("RootCertificateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save....
        /// </summary>
        internal static string SaveSignatureRequestButton {
            get {
                return ResourceManager.GetString("SaveSignatureRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Signature Requests.
        /// </summary>
        internal static string SaveSignatureRequestDialog {
            get {
                return ResourceManager.GetString("SaveSignatureRequestDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature responses have be uploaded to the server..
        /// </summary>
        internal static string SignatureResponseUploaded {
            get {
                return ResourceManager.GetString("SignatureResponseUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote.
        /// </summary>
        internal static string TallyVoteReceipt {
            get {
                return ResourceManager.GetString("TallyVoteReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulated.
        /// </summary>
        internal static string TallyVoteReceiptFoundBad {
            get {
                return ResourceManager.GetString("TallyVoteReceiptFoundBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted.
        /// </summary>
        internal static string TallyVoteReceiptFoundOk {
            get {
                return ResourceManager.GetString("TallyVoteReceiptFoundOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string TallyVoteReceiptNotFound {
            get {
                return ResourceManager.GetString("TallyVoteReceiptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ballots.
        /// </summary>
        internal static string TotalBallots {
            get {
                return ResourceManager.GetString("TotalBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid ballots.
        /// </summary>
        internal static string ValidBallots {
            get {
                return ResourceManager.GetString("ValidBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        internal static string ViewShareAuthority {
            get {
                return ResourceManager.GetString("ViewShareAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string ViewShareData {
            get {
                return ResourceManager.GetString("ViewShareData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption:.
        /// </summary>
        internal static string ViewShareEncryption {
            get {
                return ResourceManager.GetString("ViewShareEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ViewShareShare {
            get {
                return ResourceManager.GetString("ViewShareShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature:.
        /// </summary>
        internal static string ViewShareSignature {
            get {
                return ResourceManager.GetString("ViewShareSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote is now cast..
        /// </summary>
        internal static string VoteCast {
            get {
                return ResourceManager.GetString("VoteCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Description....
        /// </summary>
        internal static string VoteDescriptionButton {
            get {
                return ResourceManager.GetString("VoteDescriptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string VoteDescriptionCloseButton {
            get {
                return ResourceManager.GetString("VoteDescriptionCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string VoteDescriptionTitle {
            get {
                return ResourceManager.GetString("VoteDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        internal static string VotingListAuthorities {
            get {
                return ResourceManager.GetString("VotingListAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting list downloaded..
        /// </summary>
        internal static string VotingListDownloaded {
            get {
                return ResourceManager.GetString("VotingListDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        internal static string VotingListEnvelopes {
            get {
                return ResourceManager.GetString("VotingListEnvelopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string VotingListVoteFrom {
            get {
                return ResourceManager.GetString("VotingListVoteFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string VotingListVoteUntil {
            get {
                return ResourceManager.GetString("VotingListVoteUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string VotingStatus {
            get {
                return ResourceManager.GetString("VotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string VotingTitle {
            get {
                return ResourceManager.GetString("VotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string WizardCancelButton {
            get {
                return ResourceManager.GetString("WizardCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string WizardNextButton {
            get {
                return ResourceManager.GetString("WizardNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Previous.
        /// </summary>
        internal static string WizardPreviousButton {
            get {
                return ResourceManager.GetString("WizardPreviousButton", resourceCulture);
            }
        }
    }
}
