//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AddOptionDescription {
            get {
                return ResourceManager.GetString("AddOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string AddOptionText {
            get {
                return ResourceManager.GetString("AddOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vote Option.
        /// </summary>
        internal static string AddOptionTitle {
            get {
                return ResourceManager.GetString("AddOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a voting procedure.
        /// </summary>
        internal static string AdminChooseCreateVoting {
            get {
                return ResourceManager.GetString("AdminChooseCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download signature requests from server....
        /// </summary>
        internal static string AdminChooseDownloadSignatureRequests {
            get {
                return ResourceManager.GetString("AdminChooseDownloadSignatureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload certificate storage to server....
        /// </summary>
        internal static string AdminChooseUploadCertificateStorage {
            get {
                return ResourceManager.GetString("AdminChooseUploadCertificateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload signature response to server....
        /// </summary>
        internal static string AdminChooseUploadSignatureRessponse {
            get {
                return ResourceManager.GetString("AdminChooseUploadSignatureRessponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;heck Shares.
        /// </summary>
        internal static string AuthorityCheckShares {
            get {
                return ResourceManager.GetString("AuthorityCheckShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares were verified and accepted. Our answer was uploaded to server..
        /// </summary>
        internal static string AuthorityCheckSharesAccept {
            get {
                return ResourceManager.GetString("AuthorityCheckSharesAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares were verified but not accepted. Our answer was uploaded to server..
        /// </summary>
        internal static string AuthorityCheckSharesDecline {
            get {
                return ResourceManager.GetString("AuthorityCheckSharesDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt key shares and sign share response.
        /// </summary>
        internal static string AuthorityCheckSharesUnlockAction {
            get {
                return ResourceManager.GetString("AuthorityCheckSharesUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Shares.
        /// </summary>
        internal static string AuthorityCreateShares {
            get {
                return ResourceManager.GetString("AuthorityCreateShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of shared was canceled..
        /// </summary>
        internal static string AuthorityCreateSharesCanceled {
            get {
                return ResourceManager.GetString("AuthorityCreateSharesCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares created and uploaded them to server..
        /// </summary>
        internal static string AuthorityCreateSharesDone {
            get {
                return ResourceManager.GetString("AuthorityCreateSharesDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign newly created key shares.
        /// </summary>
        internal static string AuthorityCreateSharesUnlockAction {
            get {
                return ResourceManager.GetString("AuthorityCreateSharesUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decipher.
        /// </summary>
        internal static string AuthorityDecipher {
            get {
                return ResourceManager.GetString("AuthorityDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partial deciphering was canceled..
        /// </summary>
        internal static string AuthorityDecipherCanceled {
            get {
                return ResourceManager.GetString("AuthorityDecipherCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial deciphers were calculated and uploaded to the server..
        /// </summary>
        internal static string AuthorityDecipherDone {
            get {
                return ResourceManager.GetString("AuthorityDecipherDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign partial deciphers..
        /// </summary>
        internal static string AuthorityDecipherUnlockAction {
            get {
                return ResourceManager.GetString("AuthorityDecipherUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AuthorityListStatus {
            get {
                return ResourceManager.GetString("AuthorityListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string AuthorityListTitle {
            get {
                return ResourceManager.GetString("AuthorityListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Verify.
        /// </summary>
        internal static string AuthorityVotePreviewVerify {
            get {
                return ResourceManager.GetString("AuthorityVotePreviewVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlling Authorities.
        /// </summary>
        internal static string BadShareProofControlling {
            get {
                return ResourceManager.GetString("BadShareProofControlling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizing Administrator.
        /// </summary>
        internal static string BadShareProofOrganizing {
            get {
                return ResourceManager.GetString("BadShareProofOrganizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Authority.
        /// </summary>
        internal static string BadShareProofReporting {
            get {
                return ResourceManager.GetString("BadShareProofReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature:.
        /// </summary>
        internal static string BadShareProofSignature {
            get {
                return ResourceManager.GetString("BadShareProofSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Procedure.
        /// </summary>
        internal static string BadShareProofVoting {
            get {
                return ResourceManager.GetString("BadShareProofVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string BadShareProofVotingId {
            get {
                return ResourceManager.GetString("BadShareProofVotingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string BadShareProofVotingTitle {
            get {
                return ResourceManager.GetString("BadShareProofVotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        internal static string CertificateCreationDate {
            get {
                return ResourceManager.GetString("CertificateCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details....
        /// </summary>
        internal static string CertificateDetail {
            get {
                return ResourceManager.GetString("CertificateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CertificateFormCloseButton {
            get {
                return ResourceManager.GetString("CertificateFormCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Certificate.
        /// </summary>
        internal static string CertificateFormTitle {
            get {
                return ResourceManager.GetString("CertificateFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        internal static string CertificateId {
            get {
                return ResourceManager.GetString("CertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string CertificateInvalid {
            get {
                return ResourceManager.GetString("CertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string CertificateName {
            get {
                return ResourceManager.GetString("CertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CertificateSignatureId {
            get {
                return ResourceManager.GetString("CertificateSignatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string CertificateSignatureInvalid {
            get {
                return ResourceManager.GetString("CertificateSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CertificateSignatureName {
            get {
                return ResourceManager.GetString("CertificateSignatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures:.
        /// </summary>
        internal static string CertificateSignatures {
            get {
                return ResourceManager.GetString("CertificateSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CertificateSignatureStatus {
            get {
                return ResourceManager.GetString("CertificateSignatureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CertificateSignatureUnknown {
            get {
                return ResourceManager.GetString("CertificateSignatureUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string CertificateSignatureValid {
            get {
                return ResourceManager.GetString("CertificateSignatureValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        internal static string CertificateSignatureValidFrom {
            get {
                return ResourceManager.GetString("CertificateSignatureValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Until.
        /// </summary>
        internal static string CertificateSignatureValidUntil {
            get {
                return ResourceManager.GetString("CertificateSignatureValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate storage upload complete.
        /// </summary>
        internal static string CertificateStorageUploaded {
            get {
                return ResourceManager.GetString("CertificateStorageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string CertificateType {
            get {
                return ResourceManager.GetString("CertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string CertificateValid {
            get {
                return ResourceManager.GetString("CertificateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to create a certificate signature request and submit it to the server..
        /// </summary>
        internal static string CheckCertificateNeedRequest {
            get {
                return ResourceManager.GetString("CheckCertificateNeedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate is outdated. You need to create a new one..
        /// </summary>
        internal static string CheckCertificateOutdated {
            get {
                return ResourceManager.GetString("CheckCertificateOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate signature request ist still pending on the server..
        /// </summary>
        internal static string CheckCertificatePending {
            get {
                return ResourceManager.GetString("CheckCertificatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate is valid and ready for use..
        /// </summary>
        internal static string CheckCertificateReady {
            get {
                return ResourceManager.GetString("CheckCertificateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a response to your certificate signing request and the signature was affixed to your certificate..
        /// </summary>
        internal static string CheckCertificateResponseAccept {
            get {
                return ResourceManager.GetString("CheckCertificateResponseAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a response to your certificate signing request, but the certificate authority declined your request for the following reason:.
        /// </summary>
        internal static string CheckCertificateResponseDeclined {
            get {
                return ResourceManager.GetString("CheckCertificateResponseDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server sent a response to your certificate signing request, but it is not valid. Please context your voting administrator..
        /// </summary>
        internal static string CheckCertificateResponseInvalid {
            get {
                return ResourceManager.GetString("CheckCertificateResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate could not be validated..
        /// </summary>
        internal static string CheckCertificateResultUnknown {
            get {
                return ResourceManager.GetString("CheckCertificateResultUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate was revoked by the Certification Authority. You need to create a new one..
        /// </summary>
        internal static string CheckCertificateRevoked {
            get {
                return ResourceManager.GetString("CheckCertificateRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate contains invalid data. This might be due to data corruption..
        /// </summary>
        internal static string CheckCertificateSelfsignatureInvalid {
            get {
                return ResourceManager.GetString("CheckCertificateSelfsignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate contains invalid data. This might be due to data corruption..
        /// </summary>
        internal static string CheckCertificateSignatureDataInvalid {
            get {
                return ResourceManager.GetString("CheckCertificateSignatureDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate of your Certificate Authority is not valid..
        /// </summary>
        internal static string CheckCertificateSignerInvalid {
            get {
                return ResourceManager.GetString("CheckCertificateSignerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Certificate Authority is not known..
        /// </summary>
        internal static string CheckCertificateUnknownSigner {
            get {
                return ResourceManager.GetString("CheckCertificateUnknownSigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create....
        /// </summary>
        internal static string ChooseCertificateCreateButton {
            get {
                return ResourceManager.GetString("ChooseCertificateCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string ChooseCertificateFullName {
            get {
                return ResourceManager.GetString("ChooseCertificateFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ChooseCertificateId {
            get {
                return ResourceManager.GetString("ChooseCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificates.
        /// </summary>
        internal static string ChooseCertificateListHeader {
            get {
                return ResourceManager.GetString("ChooseCertificateListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load....
        /// </summary>
        internal static string ChooseCertificateLoadButton {
            get {
                return ResourceManager.GetString("ChooseCertificateLoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Certificate.
        /// </summary>
        internal static string ChooseCertificateLoadDialog {
            get {
                return ResourceManager.GetString("ChooseCertificateLoadDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ChooseCertificateType {
            get {
                return ResourceManager.GetString("ChooseCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfiy share &amp;proof....
        /// </summary>
        internal static string ChooseCertificateVerifyBadShareProof {
            get {
                return ResourceManager.GetString("ChooseCertificateVerifyBadShareProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string ContextMenuAdd {
            get {
                return ResourceManager.GetString("ContextMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canton:.
        /// </summary>
        internal static string CreateCertificateCanton {
            get {
                return ResourceManager.GetString("CreateCertificateCanton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted to the server. You must now wait for the certificate authority to process it..
        /// </summary>
        internal static string CreateCertificateDone {
            get {
                return ResourceManager.GetString("CreateCertificateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string CreateCertificateEmailAddress {
            get {
                return ResourceManager.GetString("CreateCertificateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me by email, when an answer to my certificate signing request is available. This requires your email address to be stored on the PiVote server..
        /// </summary>
        internal static string CreateCertificateEmailNotification {
            get {
                return ResourceManager.GetString("CreateCertificateEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string CreateCertificateFirstname {
            get {
                return ResourceManager.GetString("CreateCertificateFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party function.
        /// </summary>
        internal static string CreateCertificateFunction {
            get {
                return ResourceManager.GetString("CreateCertificateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CreateCertificateId {
            get {
                return ResourceManager.GetString("CreateCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print and Save.
        /// </summary>
        internal static string CreateCertificatePrintAndSend {
            get {
                return ResourceManager.GetString("CreateCertificatePrintAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save....
        /// </summary>
        internal static string CreateCertificateSaveButton {
            get {
                return ResourceManager.GetString("CreateCertificateSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Certificate.
        /// </summary>
        internal static string CreateCertificateSaveDialog {
            get {
                return ResourceManager.GetString("CreateCertificateSaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string CreateCertificateSurname {
            get {
                return ResourceManager.GetString("CreateCertificateSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type.
        /// </summary>
        internal static string CreateCertificateType {
            get {
                return ResourceManager.GetString("CreateCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string CreateCertificateTypeAdmin {
            get {
                return ResourceManager.GetString("CreateCertificateTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Authority.
        /// </summary>
        internal static string CreateCertificateTypeAuthority {
            get {
                return ResourceManager.GetString("CreateCertificateTypeAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter.
        /// </summary>
        internal static string CreateCertificateTypeVoter {
            get {
                return ResourceManager.GetString("CreateCertificateTypeVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention will be added automatically..
        /// </summary>
        internal static string CreateQuestionAbstentionAuto {
            get {
                return ResourceManager.GetString("CreateQuestionAbstentionAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string CreateVotingAnswers {
            get {
                return ResourceManager.GetString("CreateVotingAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers / Voter.
        /// </summary>
        internal static string CreateVotingAnswersPerVoter {
            get {
                return ResourceManager.GetString("CreateVotingAnswersPerVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority voting file missing..
        /// </summary>
        internal static string CreateVotingAuthFileMissing {
            get {
                return ResourceManager.GetString("CreateVotingAuthFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        internal static string CreateVotingAuthorities {
            get {
                return ResourceManager.GetString("CreateVotingAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create.
        /// </summary>
        internal static string CreateVotingButton {
            get {
                return ResourceManager.GetString("CreateVotingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of a voting was canceled..
        /// </summary>
        internal static string CreateVotingCanceled {
            get {
                return ResourceManager.GetString("CreateVotingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canton:.
        /// </summary>
        internal static string CreateVotingCanton {
            get {
                return ResourceManager.GetString("CreateVotingCanton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created voting on server..
        /// </summary>
        internal static string CreateVotingCreated {
            get {
                return ResourceManager.GetString("CreateVotingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating voting on server..
        /// </summary>
        internal static string CreateVotingCreating {
            get {
                return ResourceManager.GetString("CreateVotingCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CreateVotingDescription {
            get {
                return ResourceManager.GetString("CreateVotingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from.
        /// </summary>
        internal static string CreateVotingOpenFrom {
            get {
                return ResourceManager.GetString("CreateVotingOpenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        internal static string CreateVotingOpenUntil {
            get {
                return ResourceManager.GetString("CreateVotingOpenUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CreateVotingOptionDescription {
            get {
                return ResourceManager.GetString("CreateVotingOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string CreateVotingOptionText {
            get {
                return ResourceManager.GetString("CreateVotingOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string CreateVotingQuestion {
            get {
                return ResourceManager.GetString("CreateVotingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrption.
        /// </summary>
        internal static string CreateVotingQuestionDescription {
            get {
                return ResourceManager.GetString("CreateVotingQuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string CreateVotingQuestions {
            get {
                return ResourceManager.GetString("CreateVotingQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string CreateVotingQuestionText {
            get {
                return ResourceManager.GetString("CreateVotingQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching safe prime number for crypto..
        /// </summary>
        internal static string CreateVotingSearchPrime {
            get {
                return ResourceManager.GetString("CreateVotingSearchPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CreateVotingTitle {
            get {
                return ResourceManager.GetString("CreateVotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign voting parameters.
        /// </summary>
        internal static string CreateVotingUnlockAction {
            get {
                return ResourceManager.GetString("CreateVotingUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Id:.
        /// </summary>
        internal static string EncryptPrivateKeyCertificateId {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type:.
        /// </summary>
        internal static string EncryptPrivateKeyCertificateType {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt my private key.
        /// </summary>
        internal static string EncryptPrivateKeyChoose {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your private key is encrypted. You need to enter your passphrase to decrypt it..
        /// </summary>
        internal static string EncryptPrivateKeyEncrypted {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encrypt the private key of your certificate to proctet it against unauthorized use. If you do so you will be prompted to enter your passphrase when your private key is used..
        /// </summary>
        internal static string EncryptPrivateKeyInfo {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase:.
        /// </summary>
        internal static string EncryptPrivateKeyPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat passphrase:.
        /// </summary>
        internal static string EncryptPrivateKeyRepeat {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Private Key Protection.
        /// </summary>
        internal static string EncryptPrivateKeyTitle {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        internal static string EncryptPrivateKeyUnlockAction {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyUnlockAction", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ballots.
        /// </summary>
        internal static string InvalidBallots {
            get {
                return ResourceManager.GetString("InvalidBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Download.
        /// </summary>
        internal static string ListVotingDownloadMenu {
            get {
                return ResourceManager.GetString("ListVotingDownloadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The voting was downloaded successfully.
        /// </summary>
        internal static string ListVotingDownloadSuccess {
            get {
                return ResourceManager.GetString("ListVotingDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ListVotingsVotedNo {
            get {
                return ResourceManager.GetString("ListVotingsVotedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ListVotingsVotedYes {
            get {
                return ResourceManager.GetString("ListVotingsVotedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find root certificate file..
        /// </summary>
        internal static string MessageBoxRootNotFound {
            get {
                return ResourceManager.GetString("MessageBoxRootNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Certificate Storage.
        /// </summary>
        internal static string OpenCertificateStorageDialog {
            get {
                return ResourceManager.GetString("OpenCertificateStorageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Signature Responses.
        /// </summary>
        internal static string OpenSignatureResponseDialog {
            get {
                return ResourceManager.GetString("OpenSignatureResponseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention.
        /// </summary>
        internal static string OptionAbstain {
            get {
                return ResourceManager.GetString("OptionAbstain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention.
        /// </summary>
        internal static string OptionAbstainEnglish {
            get {
                return ResourceManager.GetString("OptionAbstainEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention.
        /// </summary>
        internal static string OptionAbstainFrench {
            get {
                return ResourceManager.GetString("OptionAbstainFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthaltung.
        /// </summary>
        internal static string OptionAbstainGerman {
            get {
                return ResourceManager.GetString("OptionAbstainGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstain_@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.
        /// </summary>
        internal static string OptionAbstainSpecial {
            get {
                return ResourceManager.GetString("OptionAbstainSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Client.
        /// </summary>
        internal static string PiVoteClient {
            get {
                return ResourceManager.GetString("PiVoteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save....
        /// </summary>
        internal static string SaveSignatureRequestButton {
            get {
                return ResourceManager.GetString("SaveSignatureRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Signature Requests.
        /// </summary>
        internal static string SaveSignatureRequestDialog {
            get {
                return ResourceManager.GetString("SaveSignatureRequestDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature responses were uploaded to the server..
        /// </summary>
        internal static string SignatureResponseUploaded {
            get {
                return ResourceManager.GetString("SignatureResponseUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Accepted, valid until __________________________.
        /// </summary>
        internal static string SigningRequestDocumentAccepted {
            get {
                return ResourceManager.GetString("SigningRequestDocumentAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canton:.
        /// </summary>
        internal static string SigningRequestDocumentCanton {
            get {
                return ResourceManager.GetString("SigningRequestDocumentCanton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint:.
        /// </summary>
        internal static string SigningRequestDocumentCertificateFingerprint {
            get {
                return ResourceManager.GetString("SigningRequestDocumentCertificateFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier:.
        /// </summary>
        internal static string SigningRequestDocumentCertificateId {
            get {
                return ResourceManager.GetString("SigningRequestDocumentCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string SigningRequestDocumentCertificateType {
            get {
                return ResourceManager.GetString("SigningRequestDocumentCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string SigningRequestDocumentEmailAddress {
            get {
                return ResourceManager.GetString("SigningRequestDocumentEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name:.
        /// </summary>
        internal static string SigningRequestDocumentFamilyName {
            get {
                return ResourceManager.GetString("SigningRequestDocumentFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        internal static string SigningRequestDocumentFirstName {
            get {
                return ResourceManager.GetString("SigningRequestDocumentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π-Vote.
        /// </summary>
        internal static string SigningRequestDocumentHeaderLeft {
            get {
                return ResourceManager.GetString("SigningRequestDocumentHeaderLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate Party Switzerland.
        /// </summary>
        internal static string SigningRequestDocumentHeaderRight {
            get {
                return ResourceManager.GetString("SigningRequestDocumentHeaderRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, fingerprint does not match.
        /// </summary>
        internal static string SigningRequestDocumentRefusedFingerprintMismatch {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedFingerprintMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, already has valid certificate.
        /// </summary>
        internal static string SigningRequestDocumentRefusedHasCertificate {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedHasCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, no pirate.
        /// </summary>
        internal static string SigningRequestDocumentRefusedNoPirate {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedNoPirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, not in office.
        /// </summary>
        internal static string SigningRequestDocumentRefusedNotFx {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedNotFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for certificate signing.
        /// </summary>
        internal static string SigningRequestDocumentRequest {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, passphrase forgotten.
        /// </summary>
        internal static string SigningRequestDocumentRevokedForgotten {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, presumed lost.
        /// </summary>
        internal static string SigningRequestDocumentRevokedLost {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, moved to another canton.
        /// </summary>
        internal static string SigningRequestDocumentRevokedMoved {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, no longer pirate.
        /// </summary>
        internal static string SigningRequestDocumentRevokedNoLonger {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedNoLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, no longer in office.
        /// </summary>
        internal static string SigningRequestDocumentRevokedNoMoreFx {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedNoMoreFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, presumed stolen.
        /// </summary>
        internal static string SigningRequestDocumentRevokedStolen {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Authority.
        /// </summary>
        internal static string SigningRequestDocumentSignCA {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string SigningRequestDocumentSignDate {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Authority.
        /// </summary>
        internal static string SigningRequestDocumentSignFirstAuthority {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignFirstAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        internal static string SigningRequestDocumentSignRequester {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Authority.
        /// </summary>
        internal static string SigningRequestDocumentSignSecondAuthority {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignSecondAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string SigningRequestDocumentSignSignature {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Authority.
        /// </summary>
        internal static string SigningRequestDocumentSignThirdAuthority {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignThirdAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me more options.
        /// </summary>
        internal static string SimpleChooseCertificateAdvancedOption {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateAdvancedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create.
        /// </summary>
        internal static string SimpleChooseCertificateCreateButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get a certificate signed by the certificate authority you first need to create your certificate. 
        ///
        ///Then you must fill in your personal data which is then included in your request for certificate signing. This request will be printed out and you need to meet three voting authorities which will check your identity, sign your paper request and forward it to the certificate authority.
        ///
        ///Finally you need to upload your request for certificate signing to the server to facilitate the signing process. You wil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleChooseCertificateCreateExplain {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateCreateExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a new certificate.
        /// </summary>
        internal static string SimpleChooseCertificateCreateOption {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateCreateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to vote you need a certificate proofing your identitiy..
        /// </summary>
        internal static string SimpleChooseCertificateHeader {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import.
        /// </summary>
        internal static string SimpleChooseCertificateImportButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate import successful..
        /// </summary>
        internal static string SimpleChooseCertificateImportDone {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a certificate.
        /// </summary>
        internal static string SimpleChooseCertificateImportOption {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateImportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        internal static string SimpleChooseCertificatePrintButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificatePrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upload.
        /// </summary>
        internal static string SimpleChooseCertificateUploadButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advanced Options.
        /// </summary>
        internal static string StartAdvancedOptions {
            get {
                return ResourceManager.GetString("StartAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to server could not be established.
        /// </summary>
        internal static string StartConnectError {
            get {
                return ResourceManager.GetString("StartConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server....
        /// </summary>
        internal static string StartConnecting {
            get {
                return ResourceManager.GetString("StartConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS lookup of server IP address failed.
        /// </summary>
        internal static string StartDnsError {
            get {
                return ResourceManager.GetString("StartDnsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating certificate storage....
        /// </summary>
        internal static string StartGettingCertificates {
            get {
                return ResourceManager.GetString("StartGettingCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection established.
        /// </summary>
        internal static string StartReady {
            get {
                return ResourceManager.GetString("StartReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tally only.
        /// </summary>
        internal static string StartTallyOnly {
            get {
                return ResourceManager.GetString("StartTallyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Voting.
        /// </summary>
        internal static string StartVoting {
            get {
                return ResourceManager.GetString("StartVoting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Success {
            get {
                object obj = ResourceManager.GetObject("Success", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting is tallied..
        /// </summary>
        internal static string TallyDone {
            get {
                return ResourceManager.GetString("TallyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No result from server..
        /// </summary>
        internal static string TallyNoResult {
            get {
                return ResourceManager.GetString("TallyNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote.
        /// </summary>
        internal static string TallyVoteReceipt {
            get {
                return ResourceManager.GetString("TallyVoteReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulated.
        /// </summary>
        internal static string TallyVoteReceiptFoundBad {
            get {
                return ResourceManager.GetString("TallyVoteReceiptFoundBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted.
        /// </summary>
        internal static string TallyVoteReceiptFoundOk {
            get {
                return ResourceManager.GetString("TallyVoteReceiptFoundOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string TallyVoteReceiptNotFound {
            get {
                return ResourceManager.GetString("TallyVoteReceiptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ballots.
        /// </summary>
        internal static string TotalBallots {
            get {
                return ResourceManager.GetString("TotalBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid ballots.
        /// </summary>
        internal static string ValidBallots {
            get {
                return ResourceManager.GetString("ValidBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        internal static string ViewShareData {
            get {
                return ResourceManager.GetString("ViewShareData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting material downloaded..
        /// </summary>
        internal static string ViewVotingAuthoritiesDownloaded {
            get {
                return ResourceManager.GetString("ViewVotingAuthoritiesDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The casting of the vote was canceled..
        /// </summary>
        internal static string VoteCanceled {
            get {
                return ResourceManager.GetString("VoteCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote is now cast..
        /// </summary>
        internal static string VoteCast {
            get {
                return ResourceManager.GetString("VoteCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Description....
        /// </summary>
        internal static string VoteDescriptionButton {
            get {
                return ResourceManager.GetString("VoteDescriptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string VoteDescriptionCloseButton {
            get {
                return ResourceManager.GetString("VoteDescriptionCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string VoteDescriptionTitle {
            get {
                return ResourceManager.GetString("VoteDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can vote for up to {0} options. If you don&apos;t spend them all, the remaining ones will be counted as absteentions..
        /// </summary>
        internal static string VoteMaxOptions {
            get {
                return ResourceManager.GetString("VoteMaxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one option to vote for..
        /// </summary>
        internal static string VoteSingleOption {
            get {
                return ResourceManager.GetString("VoteSingleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign vote.
        /// </summary>
        internal static string VoteUnlockAction {
            get {
                return ResourceManager.GetString("VoteUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canton.
        /// </summary>
        internal static string VotingCanton {
            get {
                return ResourceManager.GetString("VotingCanton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        internal static string VotingListAuthorities {
            get {
                return ResourceManager.GetString("VotingListAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting list downloaded..
        /// </summary>
        internal static string VotingListDownloaded {
            get {
                return ResourceManager.GetString("VotingListDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        internal static string VotingListEnvelopes {
            get {
                return ResourceManager.GetString("VotingListEnvelopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string VotingListVoteFrom {
            get {
                return ResourceManager.GetString("VotingListVoteFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        internal static string VotingListVoteUntil {
            get {
                return ResourceManager.GetString("VotingListVoteUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string VotingStatus {
            get {
                return ResourceManager.GetString("VotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string VotingTitle {
            get {
                return ResourceManager.GetString("VotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string WizardCancelButton {
            get {
                return ResourceManager.GetString("WizardCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Done.
        /// </summary>
        internal static string WizardDoneButton {
            get {
                return ResourceManager.GetString("WizardDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string WizardNextButton {
            get {
                return ResourceManager.GetString("WizardNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Previous.
        /// </summary>
        internal static string WizardPreviousButton {
            get {
                return ResourceManager.GetString("WizardPreviousButton", resourceCulture);
            }
        }
    }
}
