//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Gui.GuiResources", typeof(GuiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} valid ballots. If this number seems too low, there could be a security problem. Do not decipher the result and contact the other authorities and administrators in this case. Proceed with deciphering?.
        /// </summary>
        public static string AskForPartiallyDecipher {
            get {
                return ResourceManager.GetString("AskForPartiallyDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Done.
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        public static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        public static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        public static string CertificateCreationDate {
            get {
                return ResourceManager.GetString("CertificateCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details....
        /// </summary>
        public static string CertificateDetail {
            get {
                return ResourceManager.GetString("CertificateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string CertificateFormCloseButton {
            get {
                return ResourceManager.GetString("CertificateFormCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Certificate.
        /// </summary>
        public static string CertificateFormTitle {
            get {
                return ResourceManager.GetString("CertificateFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string CertificateId {
            get {
                return ResourceManager.GetString("CertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string CertificateInvalid {
            get {
                return ResourceManager.GetString("CertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string CertificateName {
            get {
                return ResourceManager.GetString("CertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string CertificateSignatureId {
            get {
                return ResourceManager.GetString("CertificateSignatureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string CertificateSignatureInvalid {
            get {
                return ResourceManager.GetString("CertificateSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CertificateSignatureName {
            get {
                return ResourceManager.GetString("CertificateSignatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures:.
        /// </summary>
        public static string CertificateSignatures {
            get {
                return ResourceManager.GetString("CertificateSignatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CertificateSignatureStatus {
            get {
                return ResourceManager.GetString("CertificateSignatureStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CertificateSignatureUnknown {
            get {
                return ResourceManager.GetString("CertificateSignatureUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string CertificateSignatureValid {
            get {
                return ResourceManager.GetString("CertificateSignatureValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string CertificateSignatureValidFrom {
            get {
                return ResourceManager.GetString("CertificateSignatureValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Until.
        /// </summary>
        public static string CertificateSignatureValidUntil {
            get {
                return ResourceManager.GetString("CertificateSignatureValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string CertificateType {
            get {
                return ResourceManager.GetString("CertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string CertificateValid {
            get {
                return ResourceManager.GetString("CertificateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old and now passphrase to change it..
        /// </summary>
        public static string ChangePassphraseMessageChange {
            get {
                return ResourceManager.GetString("ChangePassphraseMessageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old passphrase is wrong..
        /// </summary>
        public static string ChangePassphraseMessageWrong {
            get {
                return ResourceManager.GetString("ChangePassphraseMessageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passphrase:.
        /// </summary>
        public static string ChangePassphraseNewPassphrase {
            get {
                return ResourceManager.GetString("ChangePassphraseNewPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Passphrase:.
        /// </summary>
        public static string ChangePassphraseOldPassphrase {
            get {
                return ResourceManager.GetString("ChangePassphraseOldPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add....
        /// </summary>
        public static string ContextMenuAdd {
            get {
                return ResourceManager.GetString("ContextMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        public static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Id:.
        /// </summary>
        public static string EncryptPrivateKeyCertificateId {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type:.
        /// </summary>
        public static string EncryptPrivateKeyCertificateType {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt my private key.
        /// </summary>
        public static string EncryptPrivateKeyChoose {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your private key is encrypted. You need to enter your passphrase to decrypt it..
        /// </summary>
        public static string EncryptPrivateKeyEncrypted {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encrypt the private key of your certificate to proctet it against unauthorized use. If you do so you will be prompted to enter your passphrase when your private key is used..
        /// </summary>
        public static string EncryptPrivateKeyInfo {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase:.
        /// </summary>
        public static string EncryptPrivateKeyPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat passphrase:.
        /// </summary>
        public static string EncryptPrivateKeyRepeat {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Private Key Protection.
        /// </summary>
        public static string EncryptPrivateKeyTitle {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string EncryptPrivateKeyUnlockAction {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is wrong..
        /// </summary>
        public static string EncryptPrivateKeyWrongPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyWrongPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR code below with your smartphone to set an authentication cookie for the sign check. You may also clock the link to set an authentication cookie on your computer.
        ///Every time you generate a new sign check cookie the old will be disabled..
        /// </summary>
        public static string GenerateSignCheckDialogInfo {
            get {
                return ResourceManager.GetString("GenerateSignCheckDialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must keep this QR code and the link secret..
        /// </summary>
        public static string GenerateSignCheckDialogSecret {
            get {
                return ResourceManager.GetString("GenerateSignCheckDialogSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Sign Check.
        /// </summary>
        public static string GenerateSignCheckDialogTitle {
            get {
                return ResourceManager.GetString("GenerateSignCheckDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote.
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Client.
        /// </summary>
        public static string PiVoteClient {
            get {
                return ResourceManager.GetString("PiVoteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Request Document.
        /// </summary>
        public static string SaveDocumentDialogTitle {
            get {
                return ResourceManager.GetString("SaveDocumentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Accepted, valid until __________________________.
        /// </summary>
        public static string SigningRequestDocumentAccepted {
            get {
                return ResourceManager.GetString("SigningRequestDocumentAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier:.
        /// </summary>
        public static string SigningRequestDocumentCertificateId {
            get {
                return ResourceManager.GetString("SigningRequestDocumentCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string SigningRequestDocumentCertificateType {
            get {
                return ResourceManager.GetString("SigningRequestDocumentCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not need to send this form to the certificate authority..
        /// </summary>
        public static string SigningRequestDocumentDontSend {
            get {
                return ResourceManager.GetString("SigningRequestDocumentDontSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        public static string SigningRequestDocumentEmailAddress {
            get {
                return ResourceManager.GetString("SigningRequestDocumentEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family name:.
        /// </summary>
        public static string SigningRequestDocumentFamilyName {
            get {
                return ResourceManager.GetString("SigningRequestDocumentFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string SigningRequestDocumentFirstName {
            get {
                return ResourceManager.GetString("SigningRequestDocumentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string SigningRequestDocumentGroup {
            get {
                return ResourceManager.GetString("SigningRequestDocumentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to π-Vote.
        /// </summary>
        public static string SigningRequestDocumentHeaderLeft {
            get {
                return ResourceManager.GetString("SigningRequestDocumentHeaderLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirate Party Switzerland.
        /// </summary>
        public static string SigningRequestDocumentHeaderRight {
            get {
                return ResourceManager.GetString("SigningRequestDocumentHeaderRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you have collected the three signatures from the authorities and signed the form yourself, it must be sent to the certificate authority..
        /// </summary>
        public static string SigningRequestDocumentInfo {
            get {
                return ResourceManager.GetString("SigningRequestDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information below this line is for processing by the certificate authority. Please leave it blank..
        /// </summary>
        public static string SigningRequestDocumentLeave {
            get {
                return ResourceManager.GetString("SigningRequestDocumentLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on certificate.
        /// </summary>
        public static string SigningRequestDocumentParent {
            get {
                return ResourceManager.GetString("SigningRequestDocumentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piratenpartei Schweiz.
        /// </summary>
        public static string SigningRequestDocumentPpsAddress1 {
            get {
                return ResourceManager.GetString("SigningRequestDocumentPpsAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH-1337 Vallorbe.
        /// </summary>
        public static string SigningRequestDocumentPpsAddress2 {
            get {
                return ResourceManager.GetString("SigningRequestDocumentPpsAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, fingerprint does not match.
        /// </summary>
        public static string SigningRequestDocumentRefusedFingerprintMismatch {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedFingerprintMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, passphrase forgotten.
        /// </summary>
        public static string SigningRequestDocumentRefusedForgotten {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, already has valid certificate.
        /// </summary>
        public static string SigningRequestDocumentRefusedHasCertificate {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedHasCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, presumed lost.
        /// </summary>
        public static string SigningRequestDocumentRefusedLost {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, no member in group.
        /// </summary>
        public static string SigningRequestDocumentRefusedNoMember {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedNoMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, not in office.
        /// </summary>
        public static string SigningRequestDocumentRefusedNotFx {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedNotFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Refused, signature invalid.
        /// </summary>
        public static string SigningRequestDocumentRefusedSignatureInvalid {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRefusedSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for certificate signing.
        /// </summary>
        public static string SigningRequestDocumentRequest {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request key:.
        /// </summary>
        public static string SigningRequestDocumentRequestKey {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRequestKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, validated by error.
        /// </summary>
        public static string SigningRequestDocumentRevokedError {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, passphrase forgotten.
        /// </summary>
        public static string SigningRequestDocumentRevokedForgotten {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, presumed lost.
        /// </summary>
        public static string SigningRequestDocumentRevokedLost {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, no longer member.
        /// </summary>
        public static string SigningRequestDocumentRevokedNoLonger {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedNoLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, no longer in office.
        /// </summary>
        public static string SigningRequestDocumentRevokedNoMoreFx {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedNoMoreFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to □ Revoked, presumed stolen.
        /// </summary>
        public static string SigningRequestDocumentRevokedStolen {
            get {
                return ResourceManager.GetString("SigningRequestDocumentRevokedStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to:.
        /// </summary>
        public static string SigningRequestDocumentSendTo {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Authority.
        /// </summary>
        public static string SigningRequestDocumentSignCA {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SigningRequestDocumentSignDate {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Authority.
        /// </summary>
        public static string SigningRequestDocumentSignFirstAuthority {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignFirstAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string SigningRequestDocumentSignRequester {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Authority.
        /// </summary>
        public static string SigningRequestDocumentSignSecondAuthority {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignSecondAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string SigningRequestDocumentSignSignature {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Authority.
        /// </summary>
        public static string SigningRequestDocumentSignThirdAuthority {
            get {
                return ResourceManager.GetString("SigningRequestDocumentSignThirdAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt key shares and sign share response.
        /// </summary>
        public static string UnlockActionAuthorityCheckShares {
            get {
                return ResourceManager.GetString("UnlockActionAuthorityCheckShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign newly created key shares.
        /// </summary>
        public static string UnlockActionAuthorityCreateShares {
            get {
                return ResourceManager.GetString("UnlockActionAuthorityCreateShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign partial deciphers..
        /// </summary>
        public static string UnlockActionAuthorityDecipher {
            get {
                return ResourceManager.GetString("UnlockActionAuthorityDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign voting parameters.
        /// </summary>
        public static string UnlockActionCreateVoting {
            get {
                return ResourceManager.GetString("UnlockActionCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign command to delete voting.
        /// </summary>
        public static string UnlockActionDelete {
            get {
                return ResourceManager.GetString("UnlockActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a sign check.
        /// </summary>
        public static string UnlockActionGenerateSignCheck {
            get {
                return ResourceManager.GetString("UnlockActionGenerateSignCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign your certificate request..
        /// </summary>
        public static string UnlockActionSignRequest {
            get {
                return ResourceManager.GetString("UnlockActionSignRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign vote.
        /// </summary>
        public static string UnlockActionVote {
            get {
                return ResourceManager.GetString("UnlockActionVote", resourceCulture);
            }
        }
    }
}
