//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Circle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Circle.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a valid certificate with which you can sign your new certificate request. If you do so you not need to print out your request and get signatures from authorities but the new certificate will only be valid as long as the one you already have, that is {0:d}. Do you want to sign your signing request with your existing certificate?.
        /// </summary>
        internal static string AskToSignSignatureRequestWithParent {
            get {
                return ResourceManager.GetString("AskToSignSignatureRequestWithParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted to the server. You must now wait for the certificate authority to process it..
        /// </summary>
        internal static string CreateCertificateDone {
            get {
                return ResourceManager.GetString("CreateCertificateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string CreateCertificateEmailAddress {
            get {
                return ResourceManager.GetString("CreateCertificateEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me by email, when an answer to my certificate signing request is available. This requires your email address to be stored on the PiVote server..
        /// </summary>
        internal static string CreateCertificateEmailNotification {
            get {
                return ResourceManager.GetString("CreateCertificateEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        internal static string CreateCertificateFirstname {
            get {
                return ResourceManager.GetString("CreateCertificateFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party function.
        /// </summary>
        internal static string CreateCertificateFunction {
            get {
                return ResourceManager.GetString("CreateCertificateFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        internal static string CreateCertificateGroup {
            get {
                return ResourceManager.GetString("CreateCertificateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CreateCertificateId {
            get {
                return ResourceManager.GetString("CreateCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print and Save.
        /// </summary>
        internal static string CreateCertificatePrintAndSend {
            get {
                return ResourceManager.GetString("CreateCertificatePrintAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save....
        /// </summary>
        internal static string CreateCertificateSaveButton {
            get {
                return ResourceManager.GetString("CreateCertificateSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Certificate.
        /// </summary>
        internal static string CreateCertificateSaveDialog {
            get {
                return ResourceManager.GetString("CreateCertificateSaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string CreateCertificateSurname {
            get {
                return ResourceManager.GetString("CreateCertificateSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type.
        /// </summary>
        internal static string CreateCertificateType {
            get {
                return ResourceManager.GetString("CreateCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string CreateCertificateTypeAdmin {
            get {
                return ResourceManager.GetString("CreateCertificateTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Authority.
        /// </summary>
        internal static string CreateCertificateTypeAuthority {
            get {
                return ResourceManager.GetString("CreateCertificateTypeAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter.
        /// </summary>
        internal static string CreateCertificateTypeVoter {
            get {
                return ResourceManager.GetString("CreateCertificateTypeVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstain_@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.
        /// </summary>
        internal static string OptionAbstainSpecial {
            get {
                return ResourceManager.GetString("OptionAbstainSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover your certificate request..
        /// </summary>
        internal static string SignRequestUnlockAction {
            get {
                return ResourceManager.GetString("SignRequestUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me more options.
        /// </summary>
        internal static string SimpleChooseCertificateAdvancedOption {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateAdvancedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create.
        /// </summary>
        internal static string SimpleChooseCertificateCreateButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get a certificate signed by the certificate authority you first need to create your certificate. 
        ///
        ///Then you must fill in your personal data which is then included in your request for certificate signing. This request will be printed out and you need to meet three voting authorities which will check your identity, sign your paper request and forward it to the certificate authority.
        ///
        ///Finally you need to upload your request for certificate signing to the server to facilitate the signing process. You wil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleChooseCertificateCreateExplain {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateCreateExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I need a new certificate.
        /// </summary>
        internal static string SimpleChooseCertificateCreateOption {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateCreateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to vote you need a certificate proofing your identitiy..
        /// </summary>
        internal static string SimpleChooseCertificateHeader {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import.
        /// </summary>
        internal static string SimpleChooseCertificateImportButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate import successful..
        /// </summary>
        internal static string SimpleChooseCertificateImportDone {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I already have a certificate.
        /// </summary>
        internal static string SimpleChooseCertificateImportOption {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateImportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        internal static string SimpleChooseCertificatePrintButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificatePrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upload.
        /// </summary>
        internal static string SimpleChooseCertificateUploadButton {
            get {
                return ResourceManager.GetString("SimpleChooseCertificateUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recovery file for your certificate request is missing. You must create a new request..
        /// </summary>
        internal static string SimpleCreateCertificateFileMissing {
            get {
                return ResourceManager.GetString("SimpleCreateCertificateFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You canceled the signing of your certificate request..
        /// </summary>
        internal static string SimpleCreateCertificateSigningCanceled {
            get {
                return ResourceManager.GetString("SimpleCreateCertificateSigningCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Description....
        /// </summary>
        internal static string VoteDescriptionButton {
            get {
                return ResourceManager.GetString("VoteDescriptionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string VoteDescriptionCloseButton {
            get {
                return ResourceManager.GetString("VoteDescriptionCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string VoteDescriptionTitle {
            get {
                return ResourceManager.GetString("VoteDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can vote for up to {0} options. If you don&apos;t spend them all, the remaining ones will be counted as absteentions..
        /// </summary>
        internal static string VoteMaxOptions {
            get {
                return ResourceManager.GetString("VoteMaxOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one option to vote for..
        /// </summary>
        internal static string VoteSingleOption {
            get {
                return ResourceManager.GetString("VoteSingleOption", resourceCulture);
            }
        }
    }
}
