//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Circle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Circle.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server..
        /// </summary>
        internal static string CannotConnectMessage {
            get {
                return ResourceManager.GetString("CannotConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Backup....
        /// </summary>
        internal static string CertificateManagerBackup {
            get {
                return ResourceManager.GetString("CertificateManagerBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CertificateManagerClose {
            get {
                return ResourceManager.GetString("CertificateManagerClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group/Name.
        /// </summary>
        internal static string CertificateManagerColumnGroupName {
            get {
                return ResourceManager.GetString("CertificateManagerColumnGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string CertificateManagerColumnId {
            get {
                return ResourceManager.GetString("CertificateManagerColumnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CertificateManagerColumnStatus {
            get {
                return ResourceManager.GetString("CertificateManagerColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CertificateManagerColumnType {
            get {
                return ResourceManager.GetString("CertificateManagerColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        internal static string CertificateManagerColumnValidFrom {
            get {
                return ResourceManager.GetString("CertificateManagerColumnValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        internal static string CertificateManagerColumnValidUntil {
            get {
                return ResourceManager.GetString("CertificateManagerColumnValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create New....
        /// </summary>
        internal static string CertificateManagerCreateNew {
            get {
                return ResourceManager.GetString("CertificateManagerCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export....
        /// </summary>
        internal static string CertificateManagerExport {
            get {
                return ResourceManager.GetString("CertificateManagerExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Certificate.
        /// </summary>
        internal static string CertificateManagerExportDialogTitle {
            get {
                return ResourceManager.GetString("CertificateManagerExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import....
        /// </summary>
        internal static string CertificateManagerImport {
            get {
                return ResourceManager.GetString("CertificateManagerImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Certificate.
        /// </summary>
        internal static string CertificateManagerImportDialogTitle {
            get {
                return ResourceManager.GetString("CertificateManagerImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string CertificateManagerRefresh {
            get {
                return ResourceManager.GetString("CertificateManagerRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string CertificateManagerRemove {
            get {
                return ResourceManager.GetString("CertificateManagerRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Restore....
        /// </summary>
        internal static string CertificateManagerRestore {
            get {
                return ResourceManager.GetString("CertificateManagerRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &amp;Password....
        /// </summary>
        internal static string CertificateManagerSetPassword {
            get {
                return ResourceManager.GetString("CertificateManagerSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Certificate Manager.
        /// </summary>
        internal static string CertificateManagerTitle {
            get {
                return ResourceManager.GetString("CertificateManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinite.
        /// </summary>
        internal static string CertificateManagerValidIndefinite {
            get {
                return ResourceManager.GetString("CertificateManagerValidIndefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate is corrupt. It&apos;s status is {0}..
        /// </summary>
        internal static string CertificateStatusCorrupt {
            get {
                return ResourceManager.GetString("CertificateStatusCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Certificate.
        /// </summary>
        internal static string CertificateStatusCreateAction {
            get {
                return ResourceManager.GetString("CertificateStatusCreateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate revocation list is missing..
        /// </summary>
        internal static string CertificateStatusCrlMissing {
            get {
                return ResourceManager.GetString("CertificateStatusCrlMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a certificate yet..
        /// </summary>
        internal static string CertificateStatusNoCertificate {
            get {
                return ResourceManager.GetString("CertificateStatusNoCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your signature request is still pending..
        /// </summary>
        internal static string CertificateStatusNoSignature {
            get {
                return ResourceManager.GetString("CertificateStatusNoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate will become valid at {0}..
        /// </summary>
        internal static string CertificateStatusNotYetValid {
            get {
                return ResourceManager.GetString("CertificateStatusNotYetValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate has expired..
        /// </summary>
        internal static string CertificateStatusOutdated {
            get {
                return ResourceManager.GetString("CertificateStatusOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume Certificate Creation.
        /// </summary>
        internal static string CertificateStatusResumeAction {
            get {
                return ResourceManager.GetString("CertificateStatusResumeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your certificate has been revoked by the certificate authority..
        /// </summary>
        internal static string CertificateStatusRevoked {
            get {
                return ResourceManager.GetString("CertificateStatusRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a certificate which is valid until {0}..
        /// </summary>
        internal static string CertificateStatusValid {
            get {
                return ResourceManager.GetString("CertificateStatusValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose how thorough you want the votes checked..
        /// </summary>
        internal static string ConfigProofCountExplain {
            get {
                return ResourceManager.GetString("ConfigProofCountExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string ConfigProofCountFast {
            get {
                return ResourceManager.GetString("ConfigProofCountFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking {0} proofs means not detecting an neferious ballot with a probability of 1 in {1}..
        /// </summary>
        internal static string ConfigProofCountInfo {
            get {
                return ResourceManager.GetString("ConfigProofCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        internal static string ConfigProofCountSecure {
            get {
                return ResourceManager.GetString("ConfigProofCountSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofs.
        /// </summary>
        internal static string ConfigTabProofCount {
            get {
                return ResourceManager.GetString("ConfigTabProofCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Configuration.
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some shares were invalid. The voting will be aborted..
        /// </summary>
        internal static string ControllerCheckSharesFailed {
            get {
                return ResourceManager.GetString("ControllerCheckSharesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All shares were accepted. The voting may continue..
        /// </summary>
        internal static string ControllerCheckSharesOk {
            get {
                return ResourceManager.GetString("ControllerCheckSharesOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your signature request for certificate {0} of type {1} was accepted. You may now use your certificate..
        /// </summary>
        internal static string ControllerLoadCertificatesAccepted {
            get {
                return ResourceManager.GetString("ControllerLoadCertificatesAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your signature request for certificate {0} of type {1} was declined for the following reason: {2}.
        /// </summary>
        internal static string ControllerLoadCertificatesDeclined {
            get {
                return ResourceManager.GetString("ControllerLoadCertificatesDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request is stored on the server..
        /// </summary>
        internal static string ControllerSetSignatureRequestOk {
            get {
                return ResourceManager.GetString("ControllerSetSignatureRequestOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string ControllerStatusWorking {
            get {
                return ResourceManager.GetString("ControllerStatusWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote is cast..
        /// </summary>
        internal static string ControllerVoteCast {
            get {
                return ResourceManager.GetString("ControllerVoteCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base certificate:.
        /// </summary>
        internal static string CreateCertificateDataBaseCertificate {
            get {
                return ResourceManager.GetString("CreateCertificateDataBaseCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string CreateCertificateDataEmailAddress {
            get {
                return ResourceManager.GetString("CreateCertificateDataEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        internal static string CreateCertificateDataFamilyName {
            get {
                return ResourceManager.GetString("CreateCertificateDataFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name:.
        /// </summary>
        internal static string CreateCertificateDataFirstName {
            get {
                return ResourceManager.GetString("CreateCertificateDataFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party function:.
        /// </summary>
        internal static string CreateCertificateDataFunction {
            get {
                return ResourceManager.GetString("CreateCertificateDataFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        internal static string CreateCertificateDataGroup {
            get {
                return ResourceManager.GetString("CreateCertificateDataGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me by email, when an answer to my certificate signing request is available. This requires your email address to be stored on the PiVote server..
        /// </summary>
        internal static string CreateCertificateDataNotify {
            get {
                return ResourceManager.GetString("CreateCertificateDataNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until:.
        /// </summary>
        internal static string CreateCertificateDataValidUntil {
            get {
                return ResourceManager.GetString("CreateCertificateDataValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Create Certificate.
        /// </summary>
        internal static string CreateCertificateDialogTitle {
            get {
                return ResourceManager.GetString("CreateCertificateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address:.
        /// </summary>
        internal static string CreateCertificateFinishEmailAddress {
            get {
                return ResourceManager.GetString("CreateCertificateFinishEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate id:.
        /// </summary>
        internal static string CreateCertificateFinishId {
            get {
                return ResourceManager.GetString("CreateCertificateFinishId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to print out your signing request and upload it to the server. Then you need to collect 3 signatures from elected voting authorities on your printout and send it to the certificate authority. Once the certificate authority has accepted your request you may use your certificate to vote..
        /// </summary>
        internal static string CreateCertificateFinishInfo {
            get {
                return ResourceManager.GetString("CreateCertificateFinishInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name:.
        /// </summary>
        internal static string CreateCertificateFinishName {
            get {
                return ResourceManager.GetString("CreateCertificateFinishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        internal static string CreateCertificateFinishPrint {
            get {
                return ResourceManager.GetString("CreateCertificateFinishPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type:.
        /// </summary>
        internal static string CreateCertificateFinishType {
            get {
                return ResourceManager.GetString("CreateCertificateFinishType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Upload.
        /// </summary>
        internal static string CreateCertificateFinishUpload {
            get {
                return ResourceManager.GetString("CreateCertificateFinishUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature request data for your certificate {0} of type {1} count not be found. You must create a new certificate..
        /// </summary>
        internal static string CreateCertificateResumeFail {
            get {
                return ResourceManager.GetString("CreateCertificateResumeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Voting Authority.
        /// </summary>
        internal static string CreateCertificateSelectAuthority {
            get {
                return ResourceManager.GetString("CreateCertificateSelectAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new certificate for a voting authority. Choose this if you have been elected to be a voting authority..
        /// </summary>
        internal static string CreateCertificateSelectAuthorityInfo {
            get {
                return ResourceManager.GetString("CreateCertificateSelectAuthorityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Voter.
        /// </summary>
        internal static string CreateCertificateSelectVoter {
            get {
                return ResourceManager.GetString("CreateCertificateSelectVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new voter certificate from scratch. Choose this if you are new to Pi-Vote or your old certificate has run out..
        /// </summary>
        internal static string CreateCertificateSelectVoterInfo {
            get {
                return ResourceManager.GetString("CreateCertificateSelectVoterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter for &amp;Subgroup.
        /// </summary>
        internal static string CreateCertificateSelectVoterSubgroup {
            get {
                return ResourceManager.GetString("CreateCertificateSelectVoterSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a voter certificate for a subgroup based on a certificate you already have. Choose this if you want to create a certificate for regional or local voting..
        /// </summary>
        internal static string CreateCertificateSelectVoterSubgroupInfo {
            get {
                return ResourceManager.GetString("CreateCertificateSelectVoterSubgroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server certificate is invalid. You have to wait for the Certificate Authority to fix this problem before you can upload your request..
        /// </summary>
        internal static string CreateCertificateServerCertificateInvalidMessage {
            get {
                return ResourceManager.GetString("CreateCertificateServerCertificateInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention will be added automatically..
        /// </summary>
        internal static string CreateQuestionAbstentionAuto {
            get {
                return ResourceManager.GetString("CreateQuestionAbstentionAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers:.
        /// </summary>
        internal static string CreateVotingAnswers {
            get {
                return ResourceManager.GetString("CreateVotingAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers / Voter:.
        /// </summary>
        internal static string CreateVotingAnswersPerVoter {
            get {
                return ResourceManager.GetString("CreateVotingAnswersPerVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority voting file missing..
        /// </summary>
        internal static string CreateVotingAuthFileMissing {
            get {
                return ResourceManager.GetString("CreateVotingAuthFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities:.
        /// </summary>
        internal static string CreateVotingAuthorities {
            get {
                return ResourceManager.GetString("CreateVotingAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create.
        /// </summary>
        internal static string CreateVotingButton {
            get {
                return ResourceManager.GetString("CreateVotingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of a voting was canceled..
        /// </summary>
        internal static string CreateVotingCanceled {
            get {
                return ResourceManager.GetString("CreateVotingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string CreateVotingClearButton {
            get {
                return ResourceManager.GetString("CreateVotingClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created voting on server..
        /// </summary>
        internal static string CreateVotingCreated {
            get {
                return ResourceManager.GetString("CreateVotingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating voting on server..
        /// </summary>
        internal static string CreateVotingCreating {
            get {
                return ResourceManager.GetString("CreateVotingCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string CreateVotingDescription {
            get {
                return ResourceManager.GetString("CreateVotingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Create Voting.
        /// </summary>
        internal static string CreateVotingDialogTitle {
            get {
                return ResourceManager.GetString("CreateVotingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Generate safe prime.
        /// </summary>
        internal static string CreateVotingGeneratePrime {
            get {
                return ResourceManager.GetString("CreateVotingGeneratePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating safe prime... (Tested {0} numbers and {1} primes).
        /// </summary>
        internal static string CreateVotingGeneratingSafePrime {
            get {
                return ResourceManager.GetString("CreateVotingGeneratingSafePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        internal static string CreateVotingGroup {
            get {
                return ResourceManager.GetString("CreateVotingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following authorities are not valid on the voting begin date:.
        /// </summary>
        internal static string CreateVotingInvalidAuthorities {
            get {
                return ResourceManager.GetString("CreateVotingInvalidAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a safe prime to create voting..
        /// </summary>
        internal static string CreateVotingNotReady {
            get {
                return ResourceManager.GetString("CreateVotingNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open from:.
        /// </summary>
        internal static string CreateVotingOpenFrom {
            get {
                return ResourceManager.GetString("CreateVotingOpenFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open until:.
        /// </summary>
        internal static string CreateVotingOpenUntil {
            get {
                return ResourceManager.GetString("CreateVotingOpenUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string CreateVotingOptionDescription {
            get {
                return ResourceManager.GetString("CreateVotingOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string CreateVotingOptionText {
            get {
                return ResourceManager.GetString("CreateVotingOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Create Voting - Option.
        /// </summary>
        internal static string CreateVotingOptionTitle {
            get {
                return ResourceManager.GetString("CreateVotingOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Create Voting - Question.
        /// </summary>
        internal static string CreateVotingQuestion {
            get {
                return ResourceManager.GetString("CreateVotingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string CreateVotingQuestionDescription {
            get {
                return ResourceManager.GetString("CreateVotingQuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions:.
        /// </summary>
        internal static string CreateVotingQuestions {
            get {
                return ResourceManager.GetString("CreateVotingQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string CreateVotingQuestionText {
            get {
                return ResourceManager.GetString("CreateVotingQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safe prime ready to create voting..
        /// </summary>
        internal static string CreateVotingReady {
            get {
                return ResourceManager.GetString("CreateVotingReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching safe prime number for crypto..
        /// </summary>
        internal static string CreateVotingSearchPrime {
            get {
                return ResourceManager.GetString("CreateVotingSearchPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} safe primes in store..
        /// </summary>
        internal static string CreateVotingStored {
            get {
                return ResourceManager.GetString("CreateVotingStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Take and verify safe prime.
        /// </summary>
        internal static string CreateVotingTakePrime {
            get {
                return ResourceManager.GetString("CreateVotingTakePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string CreateVotingTitle {
            get {
                return ResourceManager.GetString("CreateVotingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url:.
        /// </summary>
        internal static string CreateVotingUrl {
            get {
                return ResourceManager.GetString("CreateVotingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying safe prime....
        /// </summary>
        internal static string CreateVotingVerifyingSafePrime {
            get {
                return ResourceManager.GetString("CreateVotingVerifyingSafePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature requests have been downloaded successfully..
        /// </summary>
        internal static string DownloadSignatureRequestsDone {
            get {
                return ResourceManager.GetString("DownloadSignatureRequestsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not matter.
        /// </summary>
        internal static string DownloadSignatureRequestsFileName {
            get {
                return ResourceManager.GetString("DownloadSignatureRequestsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save signature requests.
        /// </summary>
        internal static string DownloadSignatureRequestsSaveDialogTitle {
            get {
                return ResourceManager.GetString("DownloadSignatureRequestsSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the program. We apologize for the inconvinience. Please help us fix it by reporting it. Please send us the data in the lower text field..
        /// </summary>
        internal static string ErrorDialogInfo {
            get {
                return ResourceManager.GetString("ErrorDialogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume Creation....
        /// </summary>
        internal static string MenuCertificateResumeCreation {
            get {
                return ResourceManager.GetString("MenuCertificateResumeCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no certificate creations that can be resumed..
        /// </summary>
        internal static string MenuCertificateResumeCreationNothing {
            get {
                return ResourceManager.GetString("MenuCertificateResumeCreationNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Certificates.
        /// </summary>
        internal static string MenuCertificates {
            get {
                return ResourceManager.GetString("MenuCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create....
        /// </summary>
        internal static string MenuCertificatesCreateNew {
            get {
                return ResourceManager.GetString("MenuCertificatesCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reload.
        /// </summary>
        internal static string MenuCertificatesReload {
            get {
                return ResourceManager.GetString("MenuCertificatesReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Config.
        /// </summary>
        internal static string MenuConfig {
            get {
                return ResourceManager.GetString("MenuConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create....
        /// </summary>
        internal static string MenuCreateVoting {
            get {
                return ResourceManager.GetString("MenuCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download signature requests....
        /// </summary>
        internal static string MenuDownloadSignatureRequests {
            get {
                return ResourceManager.GetString("MenuDownloadSignatureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xtras.
        /// </summary>
        internal static string MenuExtras {
            get {
                return ResourceManager.GetString("MenuExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage....
        /// </summary>
        internal static string MenuManage {
            get {
                return ResourceManager.GetString("MenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload certificate storage....
        /// </summary>
        internal static string MenuUploadCertificateStorage {
            get {
                return ResourceManager.GetString("MenuUploadCertificateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload signature responses....
        /// </summary>
        internal static string MenuUploadSignatureResponses {
            get {
                return ResourceManager.GetString("MenuUploadSignatureResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Votings.
        /// </summary>
        internal static string MenuVotings {
            get {
                return ResourceManager.GetString("MenuVotings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string MenuVotingsRefresh {
            get {
                return ResourceManager.GetString("MenuVotingsRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open backup.
        /// </summary>
        internal static string RestoreBackupDialogTitle {
            get {
                return ResourceManager.GetString("RestoreBackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup is restored..
        /// </summary>
        internal static string RestoreBackupDone {
            get {
                return ResourceManager.GetString("RestoreBackupDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstention.
        /// </summary>
        internal static string ResultDialogAbstain {
            get {
                return ResourceManager.GetString("ResultDialogAbstain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulated.
        /// </summary>
        internal static string ResultDialogFoundBad {
            get {
                return ResourceManager.GetString("ResultDialogFoundBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counted.
        /// </summary>
        internal static string ResultDialogFoundOk {
            get {
                return ResourceManager.GetString("ResultDialogFoundOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ballots.
        /// </summary>
        internal static string ResultDialogInvalidBallots {
            get {
                return ResourceManager.GetString("ResultDialogInvalidBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not counted.
        /// </summary>
        internal static string ResultDialogNotFound {
            get {
                return ResourceManager.GetString("ResultDialogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Voting results.
        /// </summary>
        internal static string ResultDialogTitle {
            get {
                return ResourceManager.GetString("ResultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ballots.
        /// </summary>
        internal static string ResultDialogTotalBallots {
            get {
                return ResourceManager.GetString("ResultDialogTotalBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid ballots.
        /// </summary>
        internal static string ResultDialogValidBallots {
            get {
                return ResourceManager.GetString("ResultDialogValidBallots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote.
        /// </summary>
        internal static string ResultDialogYourVote {
            get {
                return ResourceManager.GetString("ResultDialogYourVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save backup.
        /// </summary>
        internal static string SaveBackupDialogTitle {
            get {
                return ResourceManager.GetString("SaveBackupDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup is saved..
        /// </summary>
        internal static string SaveBackupDone {
            get {
                return ResourceManager.GetString("SaveBackupDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Status.
        /// </summary>
        internal static string StatusDialogTitle {
            get {
                return ResourceManager.GetString("StatusDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a newer version of Circle available. Dou you wish to update from your version {0} to version {1}? If so the program will close and your browser will be directed to the update site..
        /// </summary>
        internal static string UpdateDialogText {
            get {
                return ResourceManager.GetString("UpdateDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle Update.
        /// </summary>
        internal static string UpdateDialogTitle {
            get {
                return ResourceManager.GetString("UpdateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate storage has been uploaded sucessfully..
        /// </summary>
        internal static string UploadCertificateStorageDone {
            get {
                return ResourceManager.GetString("UploadCertificateStorageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select certificate storage.
        /// </summary>
        internal static string UploadCertificateStorageOpenDialogTitle {
            get {
                return ResourceManager.GetString("UploadCertificateStorageOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature responses have been uploaded sucessfully..
        /// </summary>
        internal static string UploadSignatureResponsesDone {
            get {
                return ResourceManager.GetString("UploadSignatureResponsesDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select signature responses.
        /// </summary>
        internal static string UploadSignatureResponsesOpenDialogTitle {
            get {
                return ResourceManager.GetString("UploadSignatureResponsesOpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already voted..
        /// </summary>
        internal static string VoteAlreadyVote {
            get {
                return ResourceManager.GetString("VoteAlreadyVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Verify Shares.
        /// </summary>
        internal static string VotingActionCheck {
            get {
                return ResourceManager.GetString("VotingActionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decipher.
        /// </summary>
        internal static string VotingActionDecipher {
            get {
                return ResourceManager.GetString("VotingActionDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string VotingActionDelete {
            get {
                return ResourceManager.GetString("VotingActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Download.
        /// </summary>
        internal static string VotingActionDownload {
            get {
                return ResourceManager.GetString("VotingActionDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Shares.
        /// </summary>
        internal static string VotingActionShare {
            get {
                return ResourceManager.GetString("VotingActionShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tally.
        /// </summary>
        internal static string VotingActionTally {
            get {
                return ResourceManager.GetString("VotingActionTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vote.
        /// </summary>
        internal static string VotingActionVote {
            get {
                return ResourceManager.GetString("VotingActionVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select up to {0} options..
        /// </summary>
        internal static string VotingDialogMaxOptionMulti {
            get {
                return ResourceManager.GetString("VotingDialogMaxOptionMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one option..
        /// </summary>
        internal static string VotingDialogMaxOptionSingle {
            get {
                return ResourceManager.GetString("VotingDialogMaxOptionSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question #{0}.
        /// </summary>
        internal static string VotingDialogQuestion {
            get {
                return ResourceManager.GetString("VotingDialogQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle - Cast vote.
        /// </summary>
        internal static string VotingDialogTile {
            get {
                return ResourceManager.GetString("VotingDialogTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vote.
        /// </summary>
        internal static string VotingDialogVote {
            get {
                return ResourceManager.GetString("VotingDialogVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string VotingListCurrent {
            get {
                return ResourceManager.GetString("VotingListCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no votings to display..
        /// </summary>
        internal static string VotingListEmpty {
            get {
                return ResourceManager.GetString("VotingListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string VotingListPast {
            get {
                return ResourceManager.GetString("VotingListPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string VotingListScheduled {
            get {
                return ResourceManager.GetString("VotingListScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored.
        /// </summary>
        internal static string VotingListStored {
            get {
                return ResourceManager.GetString("VotingListStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string VotingStatusAborted {
            get {
                return ResourceManager.GetString("VotingStatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing, waiting for {0} of {1} authorities to verify shares.
        /// </summary>
        internal static string VotingStatusCheck {
            get {
                return ResourceManager.GetString("VotingStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting finished, waiting for {0} of {1} authorities to decipher.
        /// </summary>
        internal static string VotingStatusDecipher {
            get {
                return ResourceManager.GetString("VotingStatusDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished and stored offline.
        /// </summary>
        internal static string VotingStatusOffline {
            get {
                return ResourceManager.GetString("VotingStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready, voting begins on {0}.
        /// </summary>
        internal static string VotingStatusReady {
            get {
                return ResourceManager.GetString("VotingStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing, waiting for {0} of {1} authorities to create shares.
        /// </summary>
        internal static string VotingStatusShare {
            get {
                return ResourceManager.GetString("VotingStatusShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished, {0} votes can be tallied.
        /// </summary>
        internal static string VotingStatusTally {
            get {
                return ResourceManager.GetString("VotingStatusTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open for voting, {0} votes cast.
        /// </summary>
        internal static string VotingStatusVote {
            get {
                return ResourceManager.GetString("VotingStatusVote", resourceCulture);
            }
        }
    }
}
