//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching all shares..
        /// </summary>
        public static string ClientCheckSharesFetchShares {
            get {
                return ResourceManager.GetString("ClientCheckSharesFetchShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new voting status from server..
        /// </summary>
        public static string ClientCheckSharesGetVotingStatus {
            get {
                return ResourceManager.GetString("ClientCheckSharesGetVotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load authority data..
        /// </summary>
        public static string ClientCheckSharesLoadAuthority {
            get {
                return ResourceManager.GetString("ClientCheckSharesLoadAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push share response to server..
        /// </summary>
        public static string ClientCheckSharesPushShareResponse {
            get {
                return ResourceManager.GetString("ClientCheckSharesPushShareResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save authority data..
        /// </summary>
        public static string ClientCheckSharesSaveAuthority {
            get {
                return ResourceManager.GetString("ClientCheckSharesSaveAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify all shares..
        /// </summary>
        public static string ClientCheckSharesVerifyShares {
            get {
                return ResourceManager.GetString("ClientCheckSharesVerifyShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server..
        /// </summary>
        public static string ClientConnect {
            get {
                return ResourceManager.GetString("ClientConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially deciphering voting..
        /// </summary>
        public static string ClientCreateDeciphersCreatePartialDecipher {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersCreatePartialDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching all envelopes ({0} / {1}..
        /// </summary>
        public static string ClientCreateDeciphersFetchEnvelope {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching envelope count..
        /// </summary>
        public static string ClientCreateDeciphersFetchEnvelopeCount {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchEnvelopeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material..
        /// </summary>
        public static string ClientCreateDeciphersFetchMaterial {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching new voting status..
        /// </summary>
        public static string ClientCreateDeciphersFetchVotingStatus {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchVotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load authority data..
        /// </summary>
        public static string ClientCreateDeciphersLoadAuthority {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersLoadAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing partial deciphers..
        /// </summary>
        public static string ClientCreateDeciphersPushPartialDecipher {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersPushPartialDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating share parts..
        /// </summary>
        public static string ClientCreateSharePartCreateShareParts {
            get {
                return ResourceManager.GetString("ClientCreateSharePartCreateShareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching authority list..
        /// </summary>
        public static string ClientCreateSharePartFetchAuthorityList {
            get {
                return ResourceManager.GetString("ClientCreateSharePartFetchAuthorityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting new voting status..
        /// </summary>
        public static string ClientCreateSharePartGetVotingStatus {
            get {
                return ResourceManager.GetString("ClientCreateSharePartGetVotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing authority..
        /// </summary>
        public static string ClientCreateSharePartPrepareAuthority {
            get {
                return ResourceManager.GetString("ClientCreateSharePartPrepareAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing share parts..
        /// </summary>
        public static string ClientCreateSharePartPushShareParts {
            get {
                return ResourceManager.GetString("ClientCreateSharePartPushShareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving authority..
        /// </summary>
        public static string ClientCreateSharePartSaveAuthority {
            get {
                return ResourceManager.GetString("ClientCreateSharePartSaveAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voting procedure..
        /// </summary>
        public static string ClientCreateVoting {
            get {
                return ResourceManager.GetString("ClientCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting authority certificates.
        /// </summary>
        public static string ClientGetAuthorityCertificates {
            get {
                return ResourceManager.GetString("ClientGetAuthorityCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting certificate storage.
        /// </summary>
        public static string ClientGetCertificateStorage {
            get {
                return ResourceManager.GetString("ClientGetCertificateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciphering result..
        /// </summary>
        public static string ClientGetResultDecipherResult {
            get {
                return ResourceManager.GetString("ClientGetResultDecipherResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching envelope count..
        /// </summary>
        public static string ClientGetResultFetchEnvelopeCount {
            get {
                return ResourceManager.GetString("ClientGetResultFetchEnvelopeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching and verifying votes..
        /// </summary>
        public static string ClientGetResultFetchEnvelopes {
            get {
                return ResourceManager.GetString("ClientGetResultFetchEnvelopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching and verifying votes {0} / {1}..
        /// </summary>
        public static string ClientGetResultFetchEnvelopesOf {
            get {
                return ResourceManager.GetString("ClientGetResultFetchEnvelopesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material..
        /// </summary>
        public static string ClientGetResultFetchMaterial {
            get {
                return ResourceManager.GetString("ClientGetResultFetchMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching partial deciphers..
        /// </summary>
        public static string ClientGetResultFetchPartialDeciphers {
            get {
                return ResourceManager.GetString("ClientGetResultFetchPartialDeciphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching partial deciphers {0} / {1}..
        /// </summary>
        public static string ClientGetResultFetchPartialDeciphersOf {
            get {
                return ResourceManager.GetString("ClientGetResultFetchPartialDeciphersOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting material not valid..
        /// </summary>
        public static string ClientGetResultMaterialInvalid {
            get {
                return ResourceManager.GetString("ClientGetResultMaterialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting signature requests..
        /// </summary>
        public static string ClientGetSignatureRequests {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list of signature requests..
        /// </summary>
        public static string ClientGetSignatureRequestsGetList {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequestsGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting signature requests {0} / {1}..
        /// </summary>
        public static string ClientGetSignatureRequestsGetRequest {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequestsGetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature request on server..
        /// </summary>
        public static string ClientGetSignatureRequestsNoRequest {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequestsNoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set signature response..
        /// </summary>
        public static string ClientGetSignatureResponse {
            get {
                return ResourceManager.GetString("ClientGetSignatureResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting voting list..
        /// </summary>
        public static string ClientGetVotingList {
            get {
                return ResourceManager.GetString("ClientGetVotingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material and status {0} / {1}..
        /// </summary>
        public static string ClientGetVotingListFetchVoting {
            get {
                return ResourceManager.GetString("ClientGetVotingListFetchVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting ids..
        /// </summary>
        public static string ClientGetVotingListGetIds {
            get {
                return ResourceManager.GetString("ClientGetVotingListGetIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set signature request..
        /// </summary>
        public static string ClientSetSignatureRequest {
            get {
                return ResourceManager.GetString("ClientSetSignatureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting signature responses {0} / {1}..
        /// </summary>
        public static string ClientSetSignatureResponses {
            get {
                return ResourceManager.GetString("ClientSetSignatureResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature response files selected..
        /// </summary>
        public static string ClientSetSignatureResponsesNoFiles {
            get {
                return ResourceManager.GetString("ClientSetSignatureResponsesNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting vote..
        /// </summary>
        public static string ClientVote {
            get {
                return ResourceManager.GetString("ClientVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating vote..
        /// </summary>
        public static string ClientVoteCalcVote {
            get {
                return ResourceManager.GetString("ClientVoteCalcVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material..
        /// </summary>
        public static string ClientVoteFetchMaterial {
            get {
                return ResourceManager.GetString("ClientVoteFetchMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting material not valid..
        /// </summary>
        public static string ClientVoteMaterialInvalid {
            get {
                return ResourceManager.GetString("ClientVoteMaterialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing vote..
        /// </summary>
        public static string ClientVotePushVote {
            get {
                return ResourceManager.GetString("ClientVotePushVote", resourceCulture);
            }
        }
    }
}
