//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Aargau.
        /// </summary>
        public static string cantonAG {
            get {
                return ResourceManager.GetString("cantonAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Appenzell Innerrhoden.
        /// </summary>
        public static string cantonAI {
            get {
                return ResourceManager.GetString("cantonAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Appenzell Ausserrhoden.
        /// </summary>
        public static string cantonAR {
            get {
                return ResourceManager.GetString("cantonAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Bern.
        /// </summary>
        public static string cantonBE {
            get {
                return ResourceManager.GetString("cantonBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Basel-Landschaft.
        /// </summary>
        public static string cantonBL {
            get {
                return ResourceManager.GetString("cantonBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Basel-Stadt.
        /// </summary>
        public static string cantonBS {
            get {
                return ResourceManager.GetString("cantonBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Freiburg.
        /// </summary>
        public static string cantonFR {
            get {
                return ResourceManager.GetString("cantonFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Genf.
        /// </summary>
        public static string cantonGE {
            get {
                return ResourceManager.GetString("cantonGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Glarus.
        /// </summary>
        public static string cantonGL {
            get {
                return ResourceManager.GetString("cantonGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Graubünden.
        /// </summary>
        public static string cantonGR {
            get {
                return ResourceManager.GetString("cantonGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Jura.
        /// </summary>
        public static string cantonJU {
            get {
                return ResourceManager.GetString("cantonJU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Luzern.
        /// </summary>
        public static string cantonLU {
            get {
                return ResourceManager.GetString("cantonLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Neuenburg.
        /// </summary>
        public static string cantonNE {
            get {
                return ResourceManager.GetString("cantonNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only National Party.
        /// </summary>
        public static string cantonNone {
            get {
                return ResourceManager.GetString("cantonNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Nidwalden.
        /// </summary>
        public static string cantonNW {
            get {
                return ResourceManager.GetString("cantonNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Obwalden.
        /// </summary>
        public static string cantonOW {
            get {
                return ResourceManager.GetString("cantonOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party St. Gallen.
        /// </summary>
        public static string cantonSG {
            get {
                return ResourceManager.GetString("cantonSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Schaffhausen.
        /// </summary>
        public static string cantonSH {
            get {
                return ResourceManager.GetString("cantonSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Solothurn.
        /// </summary>
        public static string cantonSO {
            get {
                return ResourceManager.GetString("cantonSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Schwyz.
        /// </summary>
        public static string cantonSZ {
            get {
                return ResourceManager.GetString("cantonSZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Thurgau.
        /// </summary>
        public static string cantonTG {
            get {
                return ResourceManager.GetString("cantonTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Tessin.
        /// </summary>
        public static string cantonTI {
            get {
                return ResourceManager.GetString("cantonTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Uri.
        /// </summary>
        public static string cantonUR {
            get {
                return ResourceManager.GetString("cantonUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Waadt.
        /// </summary>
        public static string cantonVD {
            get {
                return ResourceManager.GetString("cantonVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Wallis.
        /// </summary>
        public static string cantonVS {
            get {
                return ResourceManager.GetString("cantonVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Zug.
        /// </summary>
        public static string cantonZG {
            get {
                return ResourceManager.GetString("cantonZG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantonal Party Zürich.
        /// </summary>
        public static string cantonZH {
            get {
                return ResourceManager.GetString("cantonZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string CertificateFullNameNotAvailable {
            get {
                return ResourceManager.GetString("CertificateFullNameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string CertificateTypeAdmin {
            get {
                return ResourceManager.GetString("CertificateTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting Authority.
        /// </summary>
        public static string CertificateTypeAuthority {
            get {
                return ResourceManager.GetString("CertificateTypeAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Authority.
        /// </summary>
        public static string CertificateTypeCA {
            get {
                return ResourceManager.GetString("CertificateTypeCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string CertificateTypeServer {
            get {
                return ResourceManager.GetString("CertificateTypeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CertificateTypeUnknown {
            get {
                return ResourceManager.GetString("CertificateTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voter.
        /// </summary>
        public static string CertificateTypeVoter {
            get {
                return ResourceManager.GetString("CertificateTypeVoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching all shares..
        /// </summary>
        public static string ClientCheckSharesFetchShares {
            get {
                return ResourceManager.GetString("ClientCheckSharesFetchShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new voting status from server..
        /// </summary>
        public static string ClientCheckSharesGetVotingStatus {
            get {
                return ResourceManager.GetString("ClientCheckSharesGetVotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load authority data..
        /// </summary>
        public static string ClientCheckSharesLoadAuthority {
            get {
                return ResourceManager.GetString("ClientCheckSharesLoadAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push share response to server..
        /// </summary>
        public static string ClientCheckSharesPushShareResponse {
            get {
                return ResourceManager.GetString("ClientCheckSharesPushShareResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save authority data..
        /// </summary>
        public static string ClientCheckSharesSaveAuthority {
            get {
                return ResourceManager.GetString("ClientCheckSharesSaveAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify all shares..
        /// </summary>
        public static string ClientCheckSharesVerifyShares {
            get {
                return ResourceManager.GetString("ClientCheckSharesVerifyShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server..
        /// </summary>
        public static string ClientConnect {
            get {
                return ResourceManager.GetString("ClientConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partially deciphering voting..
        /// </summary>
        public static string ClientCreateDeciphersCreatePartialDecipher {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersCreatePartialDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching all envelopes ({0} / {1}..
        /// </summary>
        public static string ClientCreateDeciphersFetchEnvelope {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching envelope count..
        /// </summary>
        public static string ClientCreateDeciphersFetchEnvelopeCount {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchEnvelopeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material..
        /// </summary>
        public static string ClientCreateDeciphersFetchMaterial {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching new voting status..
        /// </summary>
        public static string ClientCreateDeciphersFetchVotingStatus {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersFetchVotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load authority data..
        /// </summary>
        public static string ClientCreateDeciphersLoadAuthority {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersLoadAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing partial deciphers..
        /// </summary>
        public static string ClientCreateDeciphersPushPartialDecipher {
            get {
                return ResourceManager.GetString("ClientCreateDeciphersPushPartialDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating share parts..
        /// </summary>
        public static string ClientCreateSharePartCreateShareParts {
            get {
                return ResourceManager.GetString("ClientCreateSharePartCreateShareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching authority list..
        /// </summary>
        public static string ClientCreateSharePartFetchAuthorityList {
            get {
                return ResourceManager.GetString("ClientCreateSharePartFetchAuthorityList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting new voting status..
        /// </summary>
        public static string ClientCreateSharePartGetVotingStatus {
            get {
                return ResourceManager.GetString("ClientCreateSharePartGetVotingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing authority..
        /// </summary>
        public static string ClientCreateSharePartPrepareAuthority {
            get {
                return ResourceManager.GetString("ClientCreateSharePartPrepareAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing share parts..
        /// </summary>
        public static string ClientCreateSharePartPushShareParts {
            get {
                return ResourceManager.GetString("ClientCreateSharePartPushShareParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving authority..
        /// </summary>
        public static string ClientCreateSharePartSaveAuthority {
            get {
                return ResourceManager.GetString("ClientCreateSharePartSaveAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create voting procedure..
        /// </summary>
        public static string ClientCreateVoting {
            get {
                return ResourceManager.GetString("ClientCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting voting procedure..
        /// </summary>
        public static string ClientDeleteVoting {
            get {
                return ResourceManager.GetString("ClientDeleteVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching envelopes {0} / {1}.
        /// </summary>
        public static string ClientDownloadVotingFetchEnvelopesOf {
            get {
                return ResourceManager.GetString("ClientDownloadVotingFetchEnvelopesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting authority certificates.
        /// </summary>
        public static string ClientGetAuthorityCertificates {
            get {
                return ResourceManager.GetString("ClientGetAuthorityCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting certificate storage.
        /// </summary>
        public static string ClientGetCertificateStorage {
            get {
                return ResourceManager.GetString("ClientGetCertificateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciphering result..
        /// </summary>
        public static string ClientGetResultDecipherResult {
            get {
                return ResourceManager.GetString("ClientGetResultDecipherResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching envelope count..
        /// </summary>
        public static string ClientGetResultFetchEnvelopeCount {
            get {
                return ResourceManager.GetString("ClientGetResultFetchEnvelopeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching and verifying votes..
        /// </summary>
        public static string ClientGetResultFetchEnvelopes {
            get {
                return ResourceManager.GetString("ClientGetResultFetchEnvelopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching and verifying votes {0} / {1}..
        /// </summary>
        public static string ClientGetResultFetchEnvelopesOf {
            get {
                return ResourceManager.GetString("ClientGetResultFetchEnvelopesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material..
        /// </summary>
        public static string ClientGetResultFetchMaterial {
            get {
                return ResourceManager.GetString("ClientGetResultFetchMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching partial deciphers..
        /// </summary>
        public static string ClientGetResultFetchPartialDeciphers {
            get {
                return ResourceManager.GetString("ClientGetResultFetchPartialDeciphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching partial deciphers {0} / {1}..
        /// </summary>
        public static string ClientGetResultFetchPartialDeciphersOf {
            get {
                return ResourceManager.GetString("ClientGetResultFetchPartialDeciphersOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting material not valid..
        /// </summary>
        public static string ClientGetResultMaterialInvalid {
            get {
                return ResourceManager.GetString("ClientGetResultMaterialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting signature requests..
        /// </summary>
        public static string ClientGetSignatureRequests {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list of signature requests..
        /// </summary>
        public static string ClientGetSignatureRequestsGetList {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequestsGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting signature requests {0} / {1}..
        /// </summary>
        public static string ClientGetSignatureRequestsGetRequest {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequestsGetRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature request on server..
        /// </summary>
        public static string ClientGetSignatureRequestsNoRequest {
            get {
                return ResourceManager.GetString("ClientGetSignatureRequestsNoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set signature response..
        /// </summary>
        public static string ClientGetSignatureResponse {
            get {
                return ResourceManager.GetString("ClientGetSignatureResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting voting list..
        /// </summary>
        public static string ClientGetVotingList {
            get {
                return ResourceManager.GetString("ClientGetVotingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material and status {0} / {1}..
        /// </summary>
        public static string ClientGetVotingListFetchVoting {
            get {
                return ResourceManager.GetString("ClientGetVotingListFetchVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting ids..
        /// </summary>
        public static string ClientGetVotingListGetIds {
            get {
                return ResourceManager.GetString("ClientGetVotingListGetIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading certificate storage to the server..
        /// </summary>
        public static string ClientSetCertificateStorage {
            get {
                return ResourceManager.GetString("ClientSetCertificateStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set signature request..
        /// </summary>
        public static string ClientSetSignatureRequest {
            get {
                return ResourceManager.GetString("ClientSetSignatureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting signature responses {0} / {1}..
        /// </summary>
        public static string ClientSetSignatureResponses {
            get {
                return ResourceManager.GetString("ClientSetSignatureResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature response files selected..
        /// </summary>
        public static string ClientSetSignatureResponsesNoFiles {
            get {
                return ResourceManager.GetString("ClientSetSignatureResponsesNoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casting vote..
        /// </summary>
        public static string ClientVote {
            get {
                return ResourceManager.GetString("ClientVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating vote..
        /// </summary>
        public static string ClientVoteCalcVote {
            get {
                return ResourceManager.GetString("ClientVoteCalcVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching voting material..
        /// </summary>
        public static string ClientVoteFetchMaterial {
            get {
                return ResourceManager.GetString("ClientVoteFetchMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting material not valid..
        /// </summary>
        public static string ClientVoteMaterialInvalid {
            get {
                return ResourceManager.GetString("ClientVoteMaterialInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing vote..
        /// </summary>
        public static string ClientVotePushVote {
            get {
                return ResourceManager.GetString("ClientVotePushVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not allowed in current state..
        /// </summary>
        public static string CommandNotAllowedInStatus {
            get {
                return ResourceManager.GetString("CommandNotAllowedInStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command is not signed by an admin..
        /// </summary>
        public static string CommandNotFromAdmin {
            get {
                return ResourceManager.GetString("CommandNotFromAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many authorities with this voting..
        /// </summary>
        public static string ExceptionAlreadyEnoughAuthorities {
            get {
                return ResourceManager.GetString("ExceptionAlreadyEnoughAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already cast your vote..
        /// </summary>
        public static string ExceptionAlreadyVoted {
            get {
                return ResourceManager.GetString("ExceptionAlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string ExceptionArgumentNull {
            get {
                return ResourceManager.GetString("ExceptionArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string ExceptionArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied authority is already assigned to this voting..
        /// </summary>
        public static string ExceptionAuthorityAlreadyInVoting {
            get {
                return ResourceManager.GetString("ExceptionAuthorityAlreadyInVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority count does not match..
        /// </summary>
        public static string ExceptionAuthorityCountMismatch {
            get {
                return ResourceManager.GetString("ExceptionAuthorityCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied authority count out of range..
        /// </summary>
        public static string ExceptionAuthorityCountOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionAuthorityCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority has already performed this step..
        /// </summary>
        public static string ExceptionAuthorityHasAlreadyDeposited {
            get {
                return ResourceManager.GetString("ExceptionAuthorityHasAlreadyDeposited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority is not valid..
        /// </summary>
        public static string ExceptionAuthorityInvalid {
            get {
                return ResourceManager.GetString("ExceptionAuthorityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You ar not allowed to vote in the group of this voting..
        /// </summary>
        public static string ExceptionBadGroupIdInCertificate {
            get {
                return ResourceManager.GetString("ExceptionBadGroupIdInCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary data is currupted..
        /// </summary>
        public static string ExceptionBadSerializableFormat {
            get {
                return ResourceManager.GetString("ExceptionBadSerializableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting material is not valid..
        /// </summary>
        public static string ExceptionBadVotingMaterial {
            get {
                return ResourceManager.GetString("ExceptionBadVotingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is not valid..
        /// </summary>
        public static string ExceptionInvalidCertificate {
            get {
                return ResourceManager.GetString("ExceptionInvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid envelope..
        /// </summary>
        public static string ExceptionInvalidEnvelope {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnvelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid envelope. Wrong number of ballots..
        /// </summary>
        public static string ExceptionInvalidEnvelopeBadBallotCount {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnvelopeBadBallotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid envelope. Date or time are incorrect..
        /// </summary>
        public static string ExceptionInvalidEnvelopeBadDateTime {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnvelopeBadDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid envelope. Wrong number of proofs..
        /// </summary>
        public static string ExceptionInvalidEnvelopeBadProofCount {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnvelopeBadProofCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid envelope. Wrong number of votes..
        /// </summary>
        public static string ExceptionInvalidEnvelopeBadVoteCount {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnvelopeBadVoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid envelope. Voter id does not match certificate..
        /// </summary>
        public static string ExceptionInvalidEnvelopeBadVoterId {
            get {
                return ResourceManager.GetString("ExceptionInvalidEnvelopeBadVoterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature is not valid..
        /// </summary>
        public static string ExceptionInvalidSignature {
            get {
                return ResourceManager.GetString("ExceptionInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature request data not valid..
        /// </summary>
        public static string ExceptionInvalidSignatureRequest {
            get {
                return ResourceManager.GetString("ExceptionInvalidSignatureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vote receipt..
        /// </summary>
        public static string ExceptionInvalidVoteReceipt {
            get {
                return ResourceManager.GetString("ExceptionInvalidVoteReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied maximum vote number out of range..
        /// </summary>
        public static string ExceptionMaxVotaOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionMaxVotaOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authority with supplied certificate known..
        /// </summary>
        public static string ExceptionNoAuthorityWithCertificate {
            get {
                return ResourceManager.GetString("ExceptionNoAuthorityWithCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no authorized administrator..
        /// </summary>
        public static string ExceptionNoAuthorizedAdmin {
            get {
                return ResourceManager.GetString("ExceptionNoAuthorizedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied certificate is not from an authority..
        /// </summary>
        public static string ExceptionNoAuthorizedAuthority {
            get {
                return ResourceManager.GetString("ExceptionNoAuthorizedAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied certificate is not from any voter..
        /// </summary>
        public static string ExceptionNoVoterCertificate {
            get {
                return ResourceManager.GetString("ExceptionNoVoterCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting not found..
        /// </summary>
        public static string ExceptionNoVotingWithId {
            get {
                return ResourceManager.GetString("ExceptionNoVotingWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied number of options does not match..
        /// </summary>
        public static string ExceptionOptionCountMismatch {
            get {
                return ResourceManager.GetString("ExceptionOptionCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied option count out of range..
        /// </summary>
        public static string ExceptionOptionCountOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionOptionCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of envelopes does not match the partial decipher..
        /// </summary>
        public static string ExceptionPartialDecipherBadEnvelopeCount {
            get {
                return ResourceManager.GetString("ExceptionPartialDecipherBadEnvelopeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hash over all envelopes does not match the partail decipher..
        /// </summary>
        public static string ExceptionPartialDecipherBadEnvelopeHash {
            get {
                return ResourceManager.GetString("ExceptionPartialDecipherBadEnvelopeHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial decipher has a bad signature..
        /// </summary>
        public static string ExceptionPartialDecipherBadSignature {
            get {
                return ResourceManager.GetString("ExceptionPartialDecipherBadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied number is no prime..
        /// </summary>
        public static string ExceptionPIsNoPrime {
            get {
                return ResourceManager.GetString("ExceptionPIsNoPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied number is no safe prime..
        /// </summary>
        public static string ExceptionPIsNoSafePrime {
            get {
                return ResourceManager.GetString("ExceptionPIsNoSafePrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied number is no prime..
        /// </summary>
        public static string ExceptionQIsNoPrime {
            get {
                return ResourceManager.GetString("ExceptionQIsNoPrime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature request is not valid..
        /// </summary>
        public static string ExceptionRequestSignatureInvalid {
            get {
                return ResourceManager.GetString("ExceptionRequestSignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate of the server is invalid..
        /// </summary>
        public static string ExceptionServerCertificateInvalid {
            get {
                return ResourceManager.GetString("ExceptionServerCertificateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share response has bad signature..
        /// </summary>
        public static string ExceptionShareResponseBadSignature {
            get {
                return ResourceManager.GetString("ExceptionShareResponseBadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share response is negative..
        /// </summary>
        public static string ExceptionShareResponseNotAccepted {
            get {
                return ResourceManager.GetString("ExceptionShareResponseNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share response does not match voting parameters..
        /// </summary>
        public static string ExceptionShareResponseParametersDontMatch {
            get {
                return ResourceManager.GetString("ExceptionShareResponseParametersDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share response is from wrong athority..
        /// </summary>
        public static string ExceptionShareResponseWrongAuthority {
            get {
                return ResourceManager.GetString("ExceptionShareResponseWrongAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature request is not valid..
        /// </summary>
        public static string ExceptionSignatureRequestInvalid {
            get {
                return ResourceManager.GetString("ExceptionSignatureRequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested signature request was not found..
        /// </summary>
        public static string ExceptionSignatureRequestNotFound {
            get {
                return ResourceManager.GetString("ExceptionSignatureRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This signature request was already answered..
        /// </summary>
        public static string ExceptionSignatureRequestResponded {
            get {
                return ResourceManager.GetString("ExceptionSignatureRequestResponded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature request is not from proper CA..
        /// </summary>
        public static string ExceptionSignatureResponseNotFromCA {
            get {
                return ResourceManager.GetString("ExceptionSignatureResponseNotFromCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied thereshold out of range..
        /// </summary>
        public static string ExceptionTheresholdOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionTheresholdOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string ExceptionUnknown {
            get {
                return ResourceManager.GetString("ExceptionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature on vote is not valid..
        /// </summary>
        public static string ExceptionVoteSignatureNotValid {
            get {
                return ResourceManager.GetString("ExceptionVoteSignatureNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not possible in this state of voting..
        /// </summary>
        public static string ExceptionWrongStatusForOperation {
            get {
                return ResourceManager.GetString("ExceptionWrongStatusForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string LanguageFrench {
            get {
                return ResourceManager.GetString("LanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint does not match..
        /// </summary>
        public static string RefusedFingerprintNoMatch {
            get {
                return ResourceManager.GetString("RefusedFingerprintNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person has already a valid certificate..
        /// </summary>
        public static string RefusedPersonHasAlready {
            get {
                return ResourceManager.GetString("RefusedPersonHasAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is no pirate..
        /// </summary>
        public static string RefusedPersonNoPirate {
            get {
                return ResourceManager.GetString("RefusedPersonNoPirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is not in office..
        /// </summary>
        public static string RefusedPersonNotInOffice {
            get {
                return ResourceManager.GetString("RefusedPersonNotInOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request not valid..
        /// </summary>
        public static string RefusedRequestNotValid {
            get {
                return ResourceManager.GetString("RefusedRequestNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is lost..
        /// </summary>
        public static string RevokedLost {
            get {
                return ResourceManager.GetString("RevokedLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person has moved..
        /// </summary>
        public static string RevokedMoved {
            get {
                return ResourceManager.GetString("RevokedMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is no longer a pirate..
        /// </summary>
        public static string RevokedNoLonger {
            get {
                return ResourceManager.GetString("RevokedNoLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is no longer in office..
        /// </summary>
        public static string RevokedNoMoreFx {
            get {
                return ResourceManager.GetString("RevokedNoMoreFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate is stolen..
        /// </summary>
        public static string RevokedStolen {
            get {
                return ResourceManager.GetString("RevokedStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string VotingStatusAborted {
            get {
                return ResourceManager.GetString("VotingStatusAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deciphering.
        /// </summary>
        public static string VotingStatusDeciphering {
            get {
                return ResourceManager.GetString("VotingStatusDeciphering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string VotingStatusFinished {
            get {
                return ResourceManager.GetString("VotingStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string VotingStatusNew {
            get {
                return ResourceManager.GetString("VotingStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string VotingStatusOffline {
            get {
                return ResourceManager.GetString("VotingStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string VotingStatusReady {
            get {
                return ResourceManager.GetString("VotingStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing.
        /// </summary>
        public static string VotingStatusSharing {
            get {
                return ResourceManager.GetString("VotingStatusSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting.
        /// </summary>
        public static string VotingStatusVoting {
            get {
                return ResourceManager.GetString("VotingStatusVoting", resourceCulture);
            }
        }
    }
}
