//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Gui.GuiResources", typeof(GuiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        public static string AbortButton {
            get {
                return ResourceManager.GetString("AbortButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old and now passphrase to change it..
        /// </summary>
        public static string ChangePassphraseMessageChange {
            get {
                return ResourceManager.GetString("ChangePassphraseMessageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old passphrase is wrong..
        /// </summary>
        public static string ChangePassphraseMessageWrong {
            get {
                return ResourceManager.GetString("ChangePassphraseMessageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passphrase:.
        /// </summary>
        public static string ChangePassphraseNewPassphrase {
            get {
                return ResourceManager.GetString("ChangePassphraseNewPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Passphrase:.
        /// </summary>
        public static string ChangePassphraseOldPassphrase {
            get {
                return ResourceManager.GetString("ChangePassphraseOldPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Id:.
        /// </summary>
        public static string EncryptPrivateKeyCertificateId {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type:.
        /// </summary>
        public static string EncryptPrivateKeyCertificateType {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt my private key.
        /// </summary>
        public static string EncryptPrivateKeyChoose {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your private key is encrypted. You need to enter your passphrase to decrypt it..
        /// </summary>
        public static string EncryptPrivateKeyEncrypted {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encrypt the private key of your certificate to proctet it against unauthorized use. If you do so you will be prompted to enter your passphrase when your private key is used..
        /// </summary>
        public static string EncryptPrivateKeyInfo {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase:.
        /// </summary>
        public static string EncryptPrivateKeyPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat passphrase:.
        /// </summary>
        public static string EncryptPrivateKeyRepeat {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Private Key Protection.
        /// </summary>
        public static string EncryptPrivateKeyTitle {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string EncryptPrivateKeyUnlockAction {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is wrong..
        /// </summary>
        public static string EncryptPrivateKeyWrongPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyWrongPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        public static string IgnoreButton {
            get {
                return ResourceManager.GetString("IgnoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote.
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Client.
        /// </summary>
        public static string PiVoteClient {
            get {
                return ResourceManager.GetString("PiVoteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        public static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
