//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirate.PiVote.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pirate.PiVote.Gui.GuiResources", typeof(GuiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} valid ballots. If this number seems too low, there could be a security problem. Do not decipher the result and contact the other authorities and administrators in this case. Proceed with deciphering?.
        /// </summary>
        public static string AskForPartiallyDecipher {
            get {
                return ResourceManager.GetString("AskForPartiallyDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        public static string ButtonAbort {
            get {
                return ResourceManager.GetString("ButtonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Done.
        /// </summary>
        public static string ButtonDone {
            get {
                return ResourceManager.GetString("ButtonDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Ignore.
        /// </summary>
        public static string ButtonIgnore {
            get {
                return ResourceManager.GetString("ButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        public static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Retry.
        /// </summary>
        public static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        public static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter old and now passphrase to change it..
        /// </summary>
        public static string ChangePassphraseMessageChange {
            get {
                return ResourceManager.GetString("ChangePassphraseMessageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old passphrase is wrong..
        /// </summary>
        public static string ChangePassphraseMessageWrong {
            get {
                return ResourceManager.GetString("ChangePassphraseMessageWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Passphrase:.
        /// </summary>
        public static string ChangePassphraseNewPassphrase {
            get {
                return ResourceManager.GetString("ChangePassphraseNewPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Passphrase:.
        /// </summary>
        public static string ChangePassphraseOldPassphrase {
            get {
                return ResourceManager.GetString("ChangePassphraseOldPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add....
        /// </summary>
        public static string ContextMenuAdd {
            get {
                return ResourceManager.GetString("ContextMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        public static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        public static string ContextMenuRemove {
            get {
                return ResourceManager.GetString("ContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Id:.
        /// </summary>
        public static string EncryptPrivateKeyCertificateId {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Type:.
        /// </summary>
        public static string EncryptPrivateKeyCertificateType {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyCertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt my private key.
        /// </summary>
        public static string EncryptPrivateKeyChoose {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your private key is encrypted. You need to enter your passphrase to decrypt it..
        /// </summary>
        public static string EncryptPrivateKeyEncrypted {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may encrypt the private key of your certificate to proctet it against unauthorized use. If you do so you will be prompted to enter your passphrase when your private key is used..
        /// </summary>
        public static string EncryptPrivateKeyInfo {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase:.
        /// </summary>
        public static string EncryptPrivateKeyPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat passphrase:.
        /// </summary>
        public static string EncryptPrivateKeyRepeat {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Private Key Protection.
        /// </summary>
        public static string EncryptPrivateKeyTitle {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string EncryptPrivateKeyUnlockAction {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyUnlockAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passphrase is wrong..
        /// </summary>
        public static string EncryptPrivateKeyWrongPassphrase {
            get {
                return ResourceManager.GetString("EncryptPrivateKeyWrongPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote.
        /// </summary>
        public static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi-Vote Client.
        /// </summary>
        public static string PiVoteClient {
            get {
                return ResourceManager.GetString("PiVoteClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt key shares and sign share response.
        /// </summary>
        public static string UnlockActionAuthorityCheckShares {
            get {
                return ResourceManager.GetString("UnlockActionAuthorityCheckShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign newly created key shares.
        /// </summary>
        public static string UnlockActionAuthorityCreateShares {
            get {
                return ResourceManager.GetString("UnlockActionAuthorityCreateShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign partial deciphers..
        /// </summary>
        public static string UnlockActionAuthorityDecipher {
            get {
                return ResourceManager.GetString("UnlockActionAuthorityDecipher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign voting parameters.
        /// </summary>
        public static string UnlockActionCreateVoting {
            get {
                return ResourceManager.GetString("UnlockActionCreateVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign command to delete voting.
        /// </summary>
        public static string UnlockActionDelete {
            get {
                return ResourceManager.GetString("UnlockActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign your certificate request..
        /// </summary>
        public static string UnlockActionSignRequest {
            get {
                return ResourceManager.GetString("UnlockActionSignRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign vote.
        /// </summary>
        public static string UnlockActionVote {
            get {
                return ResourceManager.GetString("UnlockActionVote", resourceCulture);
            }
        }
    }
}
